- chef/cookbooks/pacemaker/libraries/chef/mixin/pacemaker/standard_cib_object.rb
- chef/cookbooks/pacemaker/providers/clone.rb
- chef/cookbooks/pacemaker/providers/colocation.rb
- chef/cookbooks/pacemaker/providers/group.rb
- chef/cookbooks/pacemaker/providers/location.rb
- chef/cookbooks/pacemaker/providers/ms.rb
- chef/cookbooks/pacemaker/providers/order.rb
- chef/cookbooks/pacemaker/providers/primitive.rb
Just some minor refactoring to clean up the code.  Also tweak a debug message.
Feel free to review but please don't merge until I've double-checked everything.
> Refactor Pacemaker LWRPs

- chef/cookbooks/drbd/attributes/default.rb
- chef/cookbooks/drbd/recipes/config.rb
- chef/cookbooks/drbd/templates/default/global_conf.erb
- chef/data_bags/crowbar/bc-template-pacemaker.json
- chef/data_bags/crowbar/bc-template-pacemaker.schema
- chef/data_bags/crowbar/migrate/pacemaker/030_add_drbd_secret.rb
- crowbar_framework/app/models/pacemaker_service.rb
Use variable sync rate config, and enable peer authentication.
> Improvements for DRBD

- crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
Obsoletes https://github.com/crowbar/crowbar-core/pull/75 and https://github.com/crowbar/crowbar-core/pull/74
> Fixed jquery event triggering

- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/recipes/default.rb
- chef/data_bags/crowbar/migrate/pacemaker/031_drop_hb_gui.rb
- chef/data_bags/crowbar/template-pacemaker.json
- chef/data_bags/crowbar/template-pacemaker.schema
- crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
- crowbar_framework/config/locales/pacemaker/en.yml
This tool doesn't exist anymore on modern systems.
> Drop support for hb_gui

- crowbar_framework/app/models/pacemaker_service.rb
This replaces the old *_available attributes.
Depends on https://github.com/crowbar/crowbar-core/pull/102
> webui: Use new Crowbar::Repository.provided_and_enabled? helper

- chef/cookbooks/crowbar-pacemaker/providers/drbd.rb
- chef/cookbooks/crowbar-pacemaker/providers/sync_mark.rb
- chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
- chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
- chef/cookbooks/pacemaker/providers/primitive.rb
- chef/cookbooks/pacemaker/recipes/stonith.rb
- crowbar_framework/app/models/pacemaker_service.rb
- crowbar_framework/app/models/pacemaker_service_object.rb
According to our now master of style, Hash#has_key? is deprecated in
favor of Hash#key?. (https://github.com/bbatsov/ruby-style-guide#hash-key)
> Avoid HoundCI bitching about has_key?

- chef/cookbooks/hawk/metadata.rb
- chef/cookbooks/pacemaker/Guardfile
- chef/cookbooks/pacemaker/libraries/chef/mixin/pacemaker/standard_cib_object.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/cib_object.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/constraint/colocation.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/constraint/location.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/constraint/order.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/resource/clone.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/resource/group.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/resource/ms.rb
- chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
- chef/cookbooks/pacemaker/spec/fixtures/clone_resource.rb
- chef/cookbooks/pacemaker/spec/fixtures/colocation_constraint.rb
- chef/cookbooks/pacemaker/spec/fixtures/keystone_primitive.rb
- chef/cookbooks/pacemaker/spec/fixtures/location_constraint.rb
- chef/cookbooks/pacemaker/spec/fixtures/ms_resource.rb
- chef/cookbooks/pacemaker/spec/fixtures/order_constraint.rb
- chef/cookbooks/pacemaker/spec/fixtures/resource_group.rb
- chef/cookbooks/pacemaker/spec/helpers/provider.rb
- chef/cookbooks/pacemaker/spec/libraries/pacemaker/cib_object_spec.rb
- chef/cookbooks/xfs/metadata.rb
Fairly generic cleanup which helps prepare for `pacemaker_transaction` LWRP.
> more misc cleanup

- crowbar_framework/app/models/pacemaker_service_object.rb
Because each chef-client runs executes everything in all cookbooks, and because
the crm calls slow things down considerably, we have a drift issue where the
founder (which does much more work since it's the only one doing the crm calls)
goes much slower than the other nodes. This can impact things badly when it's
so slow that it triggers the timeout in the sync marks.
The workaround here is to reset the sync marks on the founder, so that all
nodes wait on the sync marks and the drift is only happening between sync
marks.
The goal is to only do this when applying a proposal, so that other chef-client
runs are not blocked waiting for sync marks.
Unfortunately, there are cases where we cannot do that: for swift, it's
likely that swift-ring-compute would be on a cluster node, and since
that …
> crowbar: Workaround to avoid the drift caused by sync marks (bsc#935462)

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
This will be useful in the same way as num_corosync_nodes.
> crowbar-pacemaker: Add num_remote_nodes helper

- chef/cookbooks/crowbar-pacemaker/recipes/default.rb
- crowbar_framework/app/models/pacemaker_service.rb
- crowbar_framework/app/models/pacemaker_service_object.rb
~~Depends and contains https://github.com/crowbar/crowbar-ha/pull/60 (we need to merge separately, as gating can't work for the full patch until https://github.com/crowbar/crowbar-openstack/pull/181 is merged too).~~
~~Depends on https://github.com/crowbar/crowbar-openstack/pull/181~~
> Reset the sync marks on founder when applying proposal (bsc#935462)

- chef/cookbooks/pacemaker/libraries/pacemaker/cib_object.rb
In some very rare cases, we can get "crm configure show $foo" return
more than one CIB objects. This seems to happen for remote nodes that
have attributes.
$ crm configure show remote-d52-54-77-77-77-04
node remote-d52-54-77-77-77-04:remote \
attributes OpenStack-role=compute
primitive remote-d52-54-77-77-77-04 ocf:pacemaker:remote \
params reconnect_interval=60s server=d52-54-77-77-77-04.h9.cloud.suse.de \
op monitor interval=20s \
op start timeout=60s interval=0 \
op stop timeout=60s interval=0
To avoid this situation, we are stricter and only keep for parsing the
object definition that has the exact name
("remote-d52-54-77-77-77-04:remote" is different from
"remote-d52-54-77-77-77-04").
Unfortunately, a side effect is that we cannot use anymore the CIBObject
class to parse remote node.
> pacemaker: Be stricter when parsing "crm configure show" output

- chef/cookbooks/corosync/recipes/authkey.rb
- chef/cookbooks/corosync/recipes/authkey_generator.rb
- chef/cookbooks/corosync/recipes/authkey_writer.rb
- chef/cookbooks/crowbar-pacemaker/attributes/default.rb
- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
- chef/cookbooks/crowbar-pacemaker/recipes/default.rb
- chef/cookbooks/crowbar-pacemaker/recipes/pacemaker_authkey.rb
- chef/cookbooks/crowbar-pacemaker/recipes/quorum_policy.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote_delegator.rb
- chef/cookbooks/crowbar-pacemaker/recipes/wait_for_founder.rb
- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/recipes/authkey_generator.rb
- chef/cookbooks/pacemaker/recipes/authkey_writer.rb
- chef/cookbooks/pacemaker/recipes/remote.rb
- chef/data_bags/crowbar/migrate/pacemaker/032_add_pacemaker_remote.rb
- chef/data_bags/crowbar/template-pacemaker.json
- chef/data_bags/crowbar/template-pacemaker.schema
- chef/roles/hawk-server.rb
- chef/roles/pacemaker-cluster-member.rb
- chef/roles/pacemaker-remote-delegator.rb
- chef/roles/pacemaker-remote.rb
- crowbar_framework/app/models/pacemaker_service.rb
- crowbar_framework/config/locales/pacemaker/en.yml
This is https://github.com/crowbar/crowbar-ha/pull/53 with some fixes.
> automate pacemaker_remote setup (updated version)

- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/recipes/stonith.rb
- chef/data_bags/crowbar/migrate/pacemaker/032_add_sbd_watchdog.rb
- chef/data_bags/crowbar/template-pacemaker.json
- chef/data_bags/crowbar/template-pacemaker.schema
- crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
- crowbar_framework/config/locales/pacemaker/en.yml
Tested: surprisingly worked on the first try
> Added option to setup watchdog with SBD

- crowbar_framework/app/models/pacemaker_service_object.rb
**Depends on https://github.com/crowbar/crowbar-core/pull/193**
> Added required new methods for ha setups with remote nodes

- crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
Maybe not  worth merging yet, other changes might come there too.
So far this is only a simple fix for an intendation error in the pacemaker barclamp.
> Fix intendation

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote_delegator.rb
- chef/cookbooks/crowbar-pacemaker/recipes/sbd.rb
- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/files/default/sbd_remote.service
- chef/cookbooks/pacemaker/recipes/remote.rb
- chef/cookbooks/pacemaker/recipes/sbd.rb
- chef/cookbooks/pacemaker/recipes/stonith.rb
- chef/cookbooks/pacemaker/templates/suse/sysconfig_sbd.erb
- crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
- crowbar_framework/app/models/pacemaker_service.rb
Please note that this depends (and contains) https://github.com/crowbar/crowbar-ha/pull/55
> STONITH for remote nodes

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
- crowbar_framework/app/models/pacemaker_service_object.rb
Simplify some helper methods by avoiding unneeded blocks.
This should address https://github.com/crowbar/crowbar-ha/pull/69#discussion_r50835031
cc @jsuchome
> Code cleanups

- chef/cookbooks/crowbar-pacemaker/recipes/remote_delegator.rb
We were creating the primitive with [:create, :start]. But the devil is
in the details: with :create, we force the primitive to be created with
target-role="stopped", which results in pacemaker ensuring that the
resource is stopped. That means fencing.
So instead, we put the primitive in a transaction, which leads to the
primitive to be started automatically.
> crowbar-pacemaker: Fix fencing of remote nodes on creation of primitive

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
We add two new flags, see commit messages for the details.
> Enhance Chef::Provider::CrowbarPacemakerService for the needs of compute nodes HA

- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/recipes/setup.rb
This is based on http://docserv.suse.de/documents/SLE-HA12-SP1/SLE-HA-guide/html/cha.ha.migration.html#sec.ha.migration.upgrade.offline
> Upgrade CIB syntax version

- crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
Superseeds #82
https://bugzilla.suse.com/show_bug.cgi?id=957315
Thanks to @tboerger :)
> Limit node removal to member table

- chef/cookbooks/pacemaker/attributes/default.rb
- chef/cookbooks/pacemaker/recipes/stonith.rb
See also https://bugzilla.suse.com/show_bug.cgi?id=950185
> Setup monitoring for STONITH resources

- chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
The mod_status configuration happening at the beginning of this recipe
needs to be run on all nodes before setting up the apache HA resources.
This is quite important when upgrading from tex, as we might have an old
version of apache before the upgrade with a different syntax in the
mod_status config file. If we don't have sync marks there, then the
resource might start on nodes where the mod_status config file was not
updated, resulting in apache just failing to start due to invalid
syntax.
(And in general, it's the right thing to do anyway)
It's worth mentioning that the revision we're picking here is "good
enough", but not fully correct: technically, we don't know which
barclamp is using apache so we don't know which revision to use; but the
first time we set apache up, this sync mark …
> crowbar-pacemaker: Add sync marks to apache HA setup

- chef/cookbooks/crowbar-pacemaker/providers/drbd.rb
- chef/cookbooks/pacemaker/recipes/remote.rb
Backport of https://github.com/crowbar/crowbar-ha/pull/92 and https://github.com/crowbar/crowbar-ha/pull/94
> [3.0] Backports from master

- Gemfile
> Revert "Set rake to version to 10.3.2"

- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
(cherry picked from commit c9a9f90da9766f442f13a584e78bae638a026db3)
Backport of https://github.com/crowbar/crowbar-ha/pull/103
> [3.0] crowbar-pacemaker: Fix use of undefined variable

- chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
The mod_status configuration happening at the beginning of this recipe
needs to be run on all nodes before setting up the apache HA resources.
This is quite important when upgrading from tex, as we might have an old
version of apache before the upgrade with a different syntax in the
mod_status config file. If we don't have sync marks there, then the
resource might start on nodes where the mod_status config file was not
updated, resulting in apache just failing to start due to invalid
syntax.
(And in general, it's the right thing to do anyway)
It's worth mentioning that the revision we're picking here is "good
enough", but not fully correct: technically, we don't know which
barclamp is using apache so we don't know which revision to use; but the
first time we set apache up, this sync mark …
> [3.0] crowbar-pacemaker: Add sync marks to apache HA setup

- crowbar_framework/app/models/pacemaker_service.rb
Required for https://github.com/crowbar/crowbar-core/pull/516
> crowbar: Update for Service.Object.active_update API change

- crowbar_framework/app/models/pacemaker_service.rb
The states parameter is now useless, so drop it.
See crowbar/crowbar-core@84827646
Depends on https://github.com/crowbar/crowbar-core/pull/515
> crowbar: Update for NodeObject.add_to_run_list changes

- crowbar_framework/app/models/pacemaker_service.rb
- crowbar_framework/config/locales/pacemaker/en.yml
This extra 'E' got dropped with SLE12, so remove it to avoid confusion.
> Rename HAE to HA

- crowbar_framework/app/models/api/pacemaker.rb
- crowbar_framework/config/locales/pacemaker/en.yml
This is to be used by crowbar pre-checks, run before the upgrade
> Simple check for presence of HA-based configuration

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
- chef/cookbooks/crowbar-pacemaker/libraries/synchronization.rb
I'm not sure if this is the right place, and it is not tested yet. More like initial idea open for comments.
> Check if the node is currently in some upgrade phase and do not sync with other nodes

- crowbar_framework/app/models/api/pacemaker.rb
Previously the change was only affecting local variable.
> Correctly save new DRBD master info into the node map

- chef/cookbooks/corosync/recipes/config.rb
If the config parameters are changed, it's too risky to just restart the
cluster - this could happen on all cluster nodes at a similar time and
cause a significant outage.  Fortunately it's possible to instead reload
the config whilst keeping corosync running, via corosync-cfgtool -R.
https://bugzilla.suse.com/show_bug.cgi?id=1001164
> don't restart corosync when corosync.conf changes (bsc#1001164)

- chef/cookbooks/corosync/recipes/config.rb
If the config parameters are changed, it's too risky to just restart the
cluster - this could happen on all cluster nodes at a similar time and
cause a significant outage.  Fortunately it's possible to instead reload
the config whilst keeping corosync running, via corosync-cfgtool -R.
https://bugzilla.suse.com/show_bug.cgi?id=1001164
(cherry picked from commit d569623f863da198753cdc81cb339a028b09e62c)
backport of #160
> [3.0] don't restart corosync when corosync.conf changes (bsc#1001164)

- chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
- chef/data_bags/crowbar/migrate/pacemaker/100_stonith_in_rails.rb
- chef/data_bags/crowbar/template-pacemaker.json
- crowbar_framework/app/models/pacemaker_service.rb
- crowbar_framework/config/locales/pacemaker/en.yml
Doing it in the recipes is an issue: as they're default attributes, it means every time we need to look at these attributes, we need to run the recipes. And we will want to not run these recipes all the time in the future. For instance, https://github.com/crowbar/crowbar-core/pull/747
> Do the translation of crowbar-specific STONITH config in the rails app

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
- chef/cookbooks/crowbar-pacemaker/providers/order_only_existing.rb
This is split out of the crowbar_pacemaker_order_only_existing LWRP, to
be reusable by others.
> crowbar-pacemaker: Add CrowbarPacemakerHelper.select_existing_resources

- chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
Sync with the recent change in crowbar-core
Needed by: https://github.com/crowbar/crowbar-core/pull/1080
> upgrade: "crowbar_upgrade_step" was moved to the node role

- chef/cookbooks/crowbar-pacemaker/libraries/maintenance_mode_helpers.rb
- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Useful to expose it to other cookbooks
Use case: crowbar/crowbar-core#563
> pacemaker: move set_maintenance_mode into pacemaker helper

- chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
Without this patch, the keystone proposal often causes a crm resource
failure when it tries to start the haproxy service under pacemaker:
Failed Actions:
* haproxy_start_0 on d52-54-77-77-01-02 'not installed' (5): call=64, status=Not installed, exitreason='none',
last-rc-change='Fri Apr 28 09:53:22 2017', queued=0ms, exec=92ms
When we examine the zypper history of both controller nodes, we can see
the haproxy package may be installed by 09:53:22 on one of the nodes,
but is only installed a few seconds later on the other node, leading
pacemaker to report a failure. This patch adds sync marks (modeled after
the apache recipe in the same cookbook) to ensure pacemaker does not try
to start haproxy until both nodes are ready.
> haproxy: Add sync marks

- chef/cookbooks/corosync/recipes/authkey.rb
- chef/cookbooks/corosync/recipes/authkey_generator.rb
- chef/cookbooks/crowbar-pacemaker/providers/drbd_create_internal.rb
- chef/cookbooks/crowbar-pacemaker/recipes/mutual_ssh.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
- chef/cookbooks/drbd/recipes/resource.rb
- chef/cookbooks/pacemaker/recipes/authkey_generator.rb
From https://github.com/crowbar/crowbar-ha/pull/169 rebase + updated
> Decrease the amount of node saves

- chef/cookbooks/corosync/recipes/authkey.rb
- chef/cookbooks/corosync/recipes/authkey_generator.rb
- chef/cookbooks/crowbar-pacemaker/providers/drbd_create_internal.rb
- chef/cookbooks/crowbar-pacemaker/recipes/mutual_ssh.rb
- chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
- chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
- chef/cookbooks/drbd/recipes/resource.rb
- chef/cookbooks/pacemaker/recipes/authkey_generator.rb
Saving is expensive, so only save when needed
(cherry picked from commit 754081238726561a93fbc16a0392c01d965e7f2a)
> [4.0] Decrease the amount of node saves

- chef/cookbooks/haproxy/providers/loadbalancer.rb
- chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
Backport of https://github.com/crowbar/crowbar-ha/pull/211
> [stable/4.0] HAPproxy for SSL checks

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Backport of https://github.com/crowbar/crowbar-ha/pull/223
> [4.0] crowbar-pacemaker: Allow overriding start/stop commands for crm_resource

- chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
Up to now the haproxy resource couldn't cleanly cope with with new
virtual IPs being added for haproxy after the initial deployment.
Since we are using "pacemaker_transaction" for creating new resources
and "pacemaker_primitive" for updating existing ones there was an
ordering issue when a new VIP was added when the haproxy group already
existed. The :update for the group was not executed since VIP was not
yet created.
With MariaDB support now available this is something that can happen
quite regulary. MariaDB only needs a VIP in the "admin" network, if
later "Keystone" is deployed to the same cluster it needs an additional
VIP for the "public" network.
We're trying to fix this shortcomming now by creating the VIPs outside
of the transaction (but with target-role="Stopped") and explicitly …
> haproxy: Fix VIP creation for haproxy

- chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
Up to now the haproxy resource couldn't cleanly cope with with new
virtual IPs being added for haproxy after the initial deployment. Since
the "pacemaker_transaction" for creating new resources happened after
the "pacemaker_primitive" for updating existing ones there was an
ordering issue when a new VIP was added when the haproxy group already
existed.  The :update for the group was not executed since VIP was not
yet created.
With MariaDB support now available this is something that can happen
quite regulary. MariaDB only needs a VIP in the "admin" network, if
later "Keystone" is deployed to the same cluster it needs an additional
VIP for the "public" network.
This commit tries to address the issue by reodering the transaction and
the primitive/group resources. And by using lazy …
> [4.0] haproxy: Fix VIP creation for haproxy

- crowbar_framework/app/models/pacemaker_service.rb
> ipmi: Use discovered IP in read-only mode (forward port)

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Allows to completely skip the service restart for a pacemaker service in
case the node[cookbook_name][:disallow_restart] is set to true.
When this happens, it will save some information regarding the attempted
restart into the node[cookbook_name][:requires_restart] attribute so we
can report on services requiring restart from crowbar framework.
Depends on https://github.com/crowbar/crowbar-core/pull/1307
> crowbar-pacemaker: allow to skip restart if disallow_restart flag is set

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Allows to completely skip the service restart for a pacemaker service in
case restarts are not allowed.
This is assuming that functionality provided by crowbar/crowbar-core#1307
is merged
(cherry picked from commit d168d1c2c682ad5014c54e34f87a460d5f21806b)
Backport of: https://github.com/crowbar/crowbar-ha/pull/224
> [4.0] crowbar-pacemaker: allow to skip restart if disallow_restart flag is set

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Due to the ordering in here we were only setting the
is_pacemaker_service flag for the RestartManager in case the service was
set with use_crm_resource. That caused the real service to restart
always as we were proxying the call to the normal restart and also
caused the naming of the restart request to be mangled. As a side
effect, no matter what was happening, we were setting the node in
maintenance mode.
Instead, we move the check for allowing the restart to the first line so
we catch the restart the first thing, we save the restart with the
proper name and we avoid setting the node into maintenance mode if we
are not restarting.
(cherry picked from commit 19fe3ccb6a076906f711b0d8f0db278db13bd09f)
Backport-of: https://github.com/crowbar/crowbar-ha/pull/259/
> [4.0] crowbar-framework: fix is_pacemaker flag for RestartManager

- chef/cookbooks/crowbar-pacemaker/providers/service.rb
Due to the ordering in here we were only setting the
is_pacemaker_service flag for the RestartManager in case the service was
set with use_crm_resource. That caused the real service to restart
always as we were proxying the call to the normal restart and also
caused the naming of the restart request to be mangled. As a side
effect, no matter what was happening, we were setting the node in
maintenance mode.
Instead, we move the check for allowing the restart to the first line so
we catch the restart the first thing, we save the restart with the
proper name and we avoid setting the node into maintenance mode if we
are not restarting.
> crowbar-framework: fix is_pacemaker flag for RestartManager

- chef/data_bags/crowbar/migrate/pacemaker/201_add_ring_array.rb
This fix resolves the issue where the migration of pacemaker
proposals fail with the following error:
rake aborted!
Failed to migrate proposal data for pacemaker: error while executing migration script /opt/dell/chef/data_bags/crowbar/migrate/pacemaker/102_add_ring_array.rb:
undefined method `[]' for #<Chef::Role:0x00000008b3d618> 
/opt/dell/crowbar_framework/lib/schema_migration.rb:224:in `rescue in migrate_proposal'
> Fix for pacemaker proposal migration failure

- chef/data_bags/crowbar/migrate/pacemaker/102_add_ring_array.rb
This fix resolves the issue where the migration of pacemaker
proposals fail with the following error:
rake aborted!
Failed to migrate proposal data for pacemaker: error while executing
migration script /opt/dell/chef/data_bags/crowbar/migrate/pacemaker/
102_add_ring_array.rb:
undefined method `[]' for #<Chef::Role:0x00000008b3d618>
/opt/dell/crowbar_framework/lib/schema_migration.rb:224:in `rescue
in migrate_proposal'
(cherry picked from commit 6e5eaaf)
Backport of #266
> [4.0] Fix for pacemaker proposal migration failure

- crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
- crowbar_framework/config/locales/pacemaker/en.yml
Corosync rings can be slightly better integreated in the UI:
- adding clear sections for corosync and pacemaker, to avoid confusion
for the settings
- not using sections for "existing rings" and "new rings"
- moving the "Add" button for the new ring in the header of the list
item
- adding placeholder text for the ring entries
https://github.com/crowbar/crowbar-core/pull/1429 is required for correctly aligning the "add" button.
Old UI:
New UI:
> crowbar: Improve UI after addition of rings

- crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
- crowbar_framework/config/locales/pacemaker/en.yml
Corosync rings can be slightly better integreated in the UI:
- adding clear sections for corosync and pacemaker, to avoid confusion
for the settings
- not using sections for "existing rings" and "new rings"
- moving the "Add" button for the new ring in the header of the list
item
- adding placeholder text for the ring entries
There is no functional change, it's really just reorganizing the UI.
(cherry picked from commit 54d33cf9407ccb6007722a0504129d9e5132ac1c)
Backport of https://github.com/crowbar/crowbar-ha/pull/276
> [4.0] crowbar: Improve UI after addition of rings

- chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
Add support for downinter and tune rise/fall params.
> Haproxy attrs

- chef/cookbooks/pacemaker/libraries/pacemaker/alert.rb
- chef/cookbooks/pacemaker/providers/alert.rb
- chef/cookbooks/pacemaker/resources/alert.rb
- chef/cookbooks/pacemaker/spec/fixtures/alert.rb
- chef/cookbooks/pacemaker/spec/libraries/pacemaker/alert_spec.rb
- chef/cookbooks/pacemaker/spec/providers/alert_spec.rb
> [4.0] pacemaker: Alert resource

- chef/cookbooks/haproxy/providers/loadbalancer.rb
- chef/cookbooks/haproxy/resources/loadbalancer.rb
- chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
This backports 
- https://github.com/crowbar/crowbar-ha/pull/269
- https://github.com/crowbar/crowbar-ha/pull/279
- https://github.com/crowbar/crowbar-ha/pull/290
The maxconn part is quite important in the short term, and the downinter bit may matter soon (it also got added for galera).
> [4.0] Sync haproxy bits with master

- crowbar_framework/app/models/api/pacemaker.rb
When we introduced the new syncmarks for pacemaker
the founder was changed from a boolean indicating
that the node is a founder, to the fqdn of the founder
This results into #set_node_as_founder not working as expected
and unable to find the founder and change it to a new founder
properly
This patch refactors #set_node_as_founder to make sure we
find the old_founder and that we set the new_founder fqdn
into all the cluster nodes
> upgrade: fix pacemaker founder searchs

- crowbar_framework/app/models/api/pacemaker.rb
[:pacemaker][:founder] was changed from boolean to string recently
> [4.0] Fix a search for cluster founders.

- crowbar_framework/app/models/api/pacemaker.rb
Bug introduced with https://github.com/crowbar/crowbar-ha/pull/308/commits/f08b9a058dfec6e73520aec3e5d8ceff41cd6868
> [4.0] Fix references to Node model.

- chef/cookbooks/crowbar-pacemaker/files/default/sysctl_nonlocal_bind.conf
- chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
Deploys the haproxy in active-active mode. All nodes in cluster will have the haproxy.
Allows the migration from previous mode active-pasive
> haproxy: active-active mode

- crowbar_framework/app/models/pacemaker_service.rb
Also, do not allow more nodes in drbd cluster in the initial deployment.
> Set the value of drbd nodes only for the first deployment.

- chef/cookbooks/crowbar-pacemaker/libraries/synchronization.rb
The current "Some cluster nodes didn't set #{mark}!" isn't a very
usful message. And is a pretty common L3 bug with this simple message.
This is not very helpful for a bug report and it is a distraction from
the actual issue that happened elsewhere, as the customer could have been
looking at other nodes' logs instead of opening an SR right away.
This patch cleans up the logging to include not only the nodes that failed
but also adds the cluster name to each relevant log line. So it's clear
from the logs what pacemaker cluster the message is in reference to.
Which is useful for deployments with more then 1 HA cluster.
Adam already had a PR (202) to solve this, but unfortuantly the
underlying layout changed before it got a chance to merge. So
this patch has become a merge of both our …
> pacemaker: add failure nodes to sync fail message (bsc#1083721)

- Gemfile
Similar to https://github.com/crowbar/crowbar-core/pull/1620
> Update sprockets to avoid CVE-2018-3760

- chef/cookbooks/crowbar-pacemaker/recipes/default.rb
- chef/cookbooks/pacemaker/recipes/default.rb
When applying the pacemaker barclamp, the founder node first
(re)configures the cluster services on the local host and then
runs a [loop](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L76) waiting for two things to happen:
- the cluster to be [online](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L97)
- cluster membership to [reflect the nodes that were configured](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L100)
(or updated) in the barclamp
This cluster check is not critical - it just results in a warning
being logged if the expected cluster …
> pacemaker: don't check cluster members on founder and extend timeout for SBD case  (SCRD-8462)

- chef/cookbooks/crowbar-pacemaker/recipes/default.rb
- chef/cookbooks/pacemaker/recipes/default.rb
(backports #353)
When applying the pacemaker barclamp, the founder node first
(re)configures the cluster services on the local host and then
runs a [loop](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L76) waiting for two things to happen:
- the cluster to be [online](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L97)
- cluster membership to [reflect the nodes that were configured](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L100)
(or updated) in the barclamp
This cluster check is not critical - it just results in a warning
being logged if the …
> [5.0] pacemaker: don't check cluster members on founder and extend timeout for SBD case (SCRD-8462)

- chef/cookbooks/crowbar-pacemaker/recipes/default.rb
- chef/cookbooks/pacemaker/recipes/default.rb
(backports #354)
When applying the pacemaker barclamp, the founder node first
(re)configures the cluster services on the local host and then
runs a [loop](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L76) waiting for two things to happen:
- the cluster to be [online](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L97)
- cluster membership to [reflect the nodes that were configured](https://github.com/crowbar/crowbar-ha/blob/1b749ef337fa3ba935757a142de3bfea94169107/chef/cookbooks/pacemaker/recipes/default.rb#L100)
(or updated) in the barclamp
This cluster check is not critical - it just results in a warning
being logged if the …
> [4.0] pacemaker: don't check cluster members on founder and extend timeout for SBD case (SCRD-8462)

- chef/cookbooks/crowbar-pacemaker/providers/sync_mark.rb
- chef/cookbooks/crowbar-pacemaker/resources/sync_mark.rb
> [5.0] Make default sync_mark timeout configurable + scalable

- chef/cookbooks/crowbar-pacemaker/providers/sync_mark.rb
- chef/cookbooks/crowbar-pacemaker/resources/sync_mark.rb
> [4.0] Make default sync_mark timeout configurable + scalable

- chef/cookbooks/crowbar-pacemaker/libraries/synchronization.rb
> [5.0] Fix typo in error message
