chef/cookbooks/corosync/templates/default/corosync-shutdown-cleaner.service.erb

Service file needs absolute paths and also ExecStart has to be set to
something, even if it is not doing anything

Fix broken corosync-shutdown-cleaner.service

---

chef/cookbooks/crowbar-pacemaker/definitions/pacemaker_vip_primitive.rb

This was a very subtle and nasty bug which had gone unnoticed for a long time!  I was lucky to stumble across it whilst debugging the fallout from https://github.com/crowbar/crowbar-openstack/pull/3 - the restart of wicked dropped the admin and public VIPs for haproxy from the respective interfaces, which led me to wonder why Pacemaker didn't automatically resurrect them.
It turns out that the `vip-{admin,public}-cluster-services` primitives configured in Pacemaker were missing `op monitor interval="10s"`, but even though the `op` value was being passed to and correctly received by the `pacemaker_vip_primitive` definition, the LWRP was receiving an empty Hash even though it received all the other values correctly.
After much debugging deep in the internals of Chef, I finally realised that …

fix bug preventing VIPs from being monitored

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb

This does two things:
- reverse the logic (ie, not checking for systemd RA) since we know
the params we're looking at are specific to the OCF RA
- set the SSL-related param only for the OCF RA; it was useless for
the systemd one, afaict.

crowbar-pacemaker: Only set apache_params if RA is the OCF RA

---

chef/cookbooks/haproxy/attributes/default.rb

We reached a case again where the headers were too long and haproxy
errored out with 400 without passing the request to the backends.
Instead of increasing tune.bufsize (which is already quite high), we can
decrease tune.maxrewrite to fix it. Upstream says that 1024 is generally
enough, and that big values do create issues with long requests (like
the issue that was hit here). So decrease it a bit to avoid the current
problem.

haproxy: Decrease tune.maxrewrite from 8192 to 4096

---

chef/cookbooks/corosync/recipes/service.rb

If it's not started (just enabled), then the first shutdown will not
execute its stop command, so the block file will be there and the first
boot after installing HA will fail.

corosync: Start corosync-shutdown-cleaner.service on install

---

.travis.yml
Gemfile
Rakefile
chef/cookbooks/pacemaker/Gemfile
chef/cookbooks/pacemaker/Rakefile

When barclamp-pacemaker was migrated to crowbar-ha, there was a
regression in the Travis CI config which meant that the pacemaker
cookbook's test suite no longer got tested.  This should fix that.

reenable Pacemaker cookbook testing in Travis CI

---

chef/cookbooks/crowbar-pacemaker/providers/order_only_existing.rb
chef/cookbooks/crowbar-pacemaker/resources/order_only_existing.rb

It can be useful to have non-sequential sets of dependencies in
crowbar_pacemaker_order_only_existing, so on top of supporting
definition of ordering as Array, we also need support as String which
lets us use the full syntax of crm.
This requires some pseudo-parsing of the crm syntax to make sure we
don't drop bits that shouldn't be dropped, but also to drop empty sets
after non-existing resources have been removed.

crowbar-pacemaker: Support String for ordering of order_only_existing

---

chef/cookbooks/pacemaker/templates/opensuse/sysconfig_sbd.erb
crowbar_framework/app/models/pacemaker_service.rb

We want the same set of templates for both SUSE and openSUSE.

pacemaker: Symlink the suse templates as opensuse

---

chef/cookbooks/crowbar-pacemaker/libraries/synchronization.rb

It has been observed that non-founder members of the cluster do timeout
when waiting for founder members to complete their tasks. This patch
increases that timeout.

Increased sync_mark timeout from 60 to 180 seconds

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/cookbooks/crowbar-pacemaker/recipes/mutual_ssh.rb

Aside from the good practice of avoiding overly long recipes, we may need this as a separate reusable recipe when we add `pacemaker_remote` nodes to the cluster.  Also add a comment about `hb_report`.

extract mutual ssh code into separate recipe

---

chef/cookbooks/crowbar-pacemaker/libraries/synchronization.rb
chef/cookbooks/crowbar-pacemaker/resources/sync_mark.rb

d2c1a01 from #45 aimed to do this but it only changed one method's default value, and both methods' defaults are actually overridden by the default value from the LWRP resource definition.  However we make them all 180s for consistency, in the unlikely case anything else should call the methods directly in future.
https://bugzilla.suse.com/show_bug.cgi?id=935462

really increase sync_mark timeout to 300s (bsc#935462)

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb

This can be used when creating clones to set the clone-max metadata.

crowbar-pacemaker: Add num_corosync_nodes helper

---

chef/cookbooks/hawk/attributes/default.rb

It's better. And it's the default now, it seems.

hawk: Install hawk2

---

chef/cookbooks/crowbar-pacemaker/attributes/default.rb
chef/cookbooks/crowbar-pacemaker/recipes/default.rb

This will be useful to set the OpenStack-role attribute.
This is the bit from https://github.com/crowbar/crowbar-ha/pull/58 that can be merged right now.

crowbar-pacemaker: Add ability to set custom attributes on nodes

---

chef/cookbooks/crowbar-pacemaker/metadata.rb
chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb

~~**Note:** only last commit is of interest here for the review, the rest is from https://github.com/crowbar/crowbar-ha/pull/51 (but is required for this last commit).~~
**Note:** this goes hand in hand with https://github.com/crowbar/crowbar-openstack/pull/215
**Note:** this depends on ~~https://github.com/crowbar/crowbar-ha/pull/56~~
Because the pacemaker resources for haproxy and apache are created here
in crowbar-pacemaker, we, in theory, shouldn't assume there that these
two services will be used for OpenStack and so we can't always just add
the location constraint to tell pacemaker to only run these on
controller nodes.
However, we do need the constraints when it's OpenStack. So crowbar will
add a flag to tell us to add these constraints, and when it's there, we
do what we're asked …

crowbar-pacemaker: Add location constraint for haproxy & apache

---

crowbar_framework/app/models/pacemaker_service_object.rb

This is used when orchestrating the application of a role that include
remotes: we then need to find the matching cluster to run some followup
action.

crowbar: Add cluster_from_remotes helper

---

chef/cookbooks/pacemaker/libraries/pacemaker/transaction.rb

On Windows (where the pacemaker cookbook is loaded due to dependencies),
we don't seem to have a stack that supports keyword arguments. So don't
use this.

pacemaker: Keep compatibility with older version of ruby

---

chef/cookbooks/pacemaker/providers/transaction.rb
chef/cookbooks/pacemaker/spec/helpers/crm_mocks.rb
chef/cookbooks/pacemaker/spec/providers/transaction_spec.rb

Previous code was using ::Pacemaker::CIBObject.exists? for each object
in the transaction, which calls "crm configure show" that many times.
crm being a python tool, it can take some time to start, and doing that
so many times is not very optimal. So just run it once and filter the
output to get a list of existing objects.

pacemaker: Only call "crm configure show" once per transaction

---

crowbar_framework/app/models/pacemaker_service.rb

If remote nodes of a cluster are assigned to a compute role (for instance), then when we add a new remote node, this remote node should also get the compute role automatically.

Make new remote nodes get the already existing roles applied for remote cluster

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb

This is useful to have hawk / crm not be confused by remote nodes which
should not use the clones.

crowbar-pacemaker: Set clone-max metadata for clone resources

---

chef/cookbooks/crowbar-pacemaker/libraries/maintenance_mode_helpers.rb

If there's no value for the attribute, we get:
Error performing operation: No such device or address
To avoid this, we simply tell crm_attribute what is the default value.

crowbar-pacemaker: Improve maintenance check with a default value

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb

This is not needed, but is slightly nicer since when we run commands on
each node, then we know the order to expect.

crowbar-pacemaker: Sort nodes returned by cluster_nodes/remote_nodes

---

chef/cookbooks/pacemaker/libraries/chef/mixin/pacemaker/standard_cib_object.rb
chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource/primitive_spec.rb

See both commit messages for the details on the two issues that are fixed.

pacemaker: Avoid calling crm for redefining resources while there's no diff

---

chef/cookbooks/crowbar-pacemaker/libraries/maintenance_mode_helpers.rb

We need to check the maintenance flag on the right pacemaker node name.

crowbar-pacemaker: Fix maintenance_mode? helper for remote nodes

---

chef/data_bags/crowbar/migrate/pacemaker/030_add_drbd_secret.rb

We were not generating a new secret on migration, resulting in an empty
secret.

crowbar: Fix migrating adding drbd secret

---

chef/cookbooks/pacemaker/recipes/remote.rb

Pacemaker currently makes it too easy to take over a remote, simply by connecting to its TCP port.  So until that bug is fixed, we should avoid making an actual connection, and instead simply check via `lsof` that the port is being listened on.
https://bugzilla.suse.com/show_bug.cgi?id=967388

avoid spurious connections to pacemaker_remoted (bsc#967388)

---

chef/cookbooks/pacemaker/recipes/remote.rb

This eliminates the very small corner case that an unexpected connection
was established from one remote node to another, e.g. manually for
testing.

only check for Pacemaker remote TCP port in LISTEN state

---

chef/cookbooks/crowbar-pacemaker/providers/drbd.rb

I'm not 100% sure this is the right approach yet, but it's probably better than nothing.  I don't get why the fenced founder loses its `pacemaker-cluster-member` role, since it's showing in Ready state (despite `crowbar_join` bailing at the `/var/spool/corosync/block_automatic_start` test).  (I can't find anything in any logs explaining why the role was removed from node1.)  But that means that the Chef search on the non-founder to find a DRBD peer fails to find the founder.  At this point I'm not sure whether it's better to keep the previous value of `remote_host` (as this PR does), or fail the chef-client run.  But either way we need to improve the error handling.

Handle DRBD in degraded cluster better

---

Gemfile

This change is needed due to the incompatibility with rake 11.0.0.

Set rake to version to 10.3.2

---

chef/cookbooks/pacemaker/templates/default/crm-initial.conf.erb

**DO NOT MERGE YET - this is a significant cluster-wide change which needs thorough failover testing, and may even be too invasive to backport to SOC6 or 5.**
If `neutron-ha-tool` fails to start (e.g. because `neutron-server` is not yet listening on a socket due the daemon still being in the startup phase) then we should retry a few times on the same node, rather than immediately migrating to the other node. We already have `migration-threshold` defaulting to 3, which makes sense in this case.
Also in general, retrying startup of services seems like a good idea. Retries happen immediately so it should not significantly slow down fail-overs and increase service downtime.  If in the future we only want to allow retries for certain resources, we can change the cluster-wide default …

Make Pacemaker retry start actions if they fail (bsc#965886)

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb

**NEEDS TESTING**
(There is [a corresponding commit to crowbar-openstack](https://github.com/crowbar/crowbar-openstack/pull/330), in which there are many more clones than in this repository.)
By default, Pacemaker clones aren't interleaved.  This means that if Pacemaker wants to restart a dead clone instance, and there is an order constraint on that clone, it will do the same restart on all other nodes, even if all the others are healthy.
More details on interleaving are here:
- https://www.hastexo.com/resources/hints-and-kinks/interleaving-pacemaker-clones/
This behaviour is far more disruptive than we want.  For example, in [bsc#965886 (L3: neutron-ha-tool not migrating dhcp networks during failover)](https://bugzilla.suse.com/show_bug.cgi?id=965886) we saw that when a network node dies …

interleave Apache clones to minimise disruption (bsc#965886)

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb

(There is a corresponding commit to crowbar-openstack, in which
there are many more clones than in this repository.)
By default, Pacemaker clones aren't interleaved.  This means that if
Pacemaker wants to restart a dead clone instance, and there is an order
constraint on that clone, it will do the same restart on all other
nodes, even if all the others are healthy.
More details on interleaving are here:
https://www.hastexo.com/resources/hints-and-kinks/interleaving-pacemaker-clones/
This behaviour is far more disruptive than we want.  For example, in
https://bugzilla.suse.com/show_bug.cgi?id=965886
we saw that when a network node dies and Pacemaker wants to stop the
instance of cl-g-neutron-agents on that node, it also stops and restarts
the same clone instances on the healthy nodes. …

[3.0] interleave Apache clones to minimise disruption (bsc#965886)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

We were using the http-request for haproxy with a 5s timeout. This
option only addresses the initial part of the HTTP negotiation. Once
the HTTP session is established we should use a shorter timeout
for idling connections with the http-keep-alive option. This option
if not set gets the same value as http-request timeout.
This patch will help fix problems with 'nova boot --poll', because
the connections usually ended at the same time a new request was
coming, leading to connection refused errors.
References:
- https://trello.com/c/m9a3MQYS
- https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-timeout%20http-keep-alive

Added http-keep-alive option to haproxy defaults

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

We were using the http-request for haproxy with a 5s timeout. This
option only addresses the initial part of the HTTP negotiation. Once
the HTTP session is established we should use a shorter timeout
for idling connections with the http-keep-alive option. This option
if not set gets the same value as http-request timeout.
This patch will help fix problems with 'nova boot --poll', because
the connections usually ended at the same time a new request was
coming, leading to connection refused errors.
References:
- https://trello.com/c/m9a3MQYS
- https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-timeout%20http-keep-alive

[3.0] Added http-keep-alive option to haproxy defaults

---

chef/cookbooks/pacemaker/templates/default/crm-initial.conf.erb

**Backport of #102 to 3.0**
If neutron-ha-tool fails to start (e.g. because `neutron-server` is not yet listening on a socket due the daemon still being in the startup phase) then we should retry a few times on the same node, rather than immediately migrating to the other node. We already have migration-threshold defaulting to 3, which makes sense in this case:
https://bugzilla.suse.com/show_bug.cgi?id=965886
However this is not a fully reliable fix, since it's conceivable that the daemon could stay in the startup phase for longer than (migration-threshold * number-of-nodes) retries.  So we will also need to make start-up of `neutron-server` (and maybe other daemons) asynchronous, i.e. blocking until the API endpoint is actually usable.
OTOH, in general retrying startup of services seems …

[3.0] Make Pacemaker retry start actions if they fail (bsc#965886)

---

chef/cookbooks/crowbar-pacemaker/metadata.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_hawk_server.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_pacemaker_cluster_member.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_pacemaker_remote.rb
chef/roles/hawk-server.rb
chef/roles/pacemaker-cluster-member.rb
chef/roles/pacemaker-remote.rb

We want the roles to only reference one recipe, so that we can put some
intelligence in that recipe:
- in a first step, we will stop changing the run list of a node
depending on its state, and instead have the role recipe "decide"
whether something should be done or not, depending on the state. This
will solve the issue that the search results for nodes are not
reliable when a node is in some state that is not "readying",
"applying" or "ready".
Very concretely: many recipes are using searches to find attributes
of another barclamp. The recipes do not expect the search to return
an empty result (and that's okay, because we know that there must be
a glance server when we deploy nova, due to barclamp dependencies),
but that could happen in the past when the node was in "problem" or …

Add "role recipes" with the goal of simplifying the roles

---

Gemfile
Rakefile

Since we switched to SLE12 we can use the faster uglifier which uses
NodeJS.

Switch from closure-compiler to uglifier

---

chef/cookbooks/crowbar-pacemaker/metadata.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_hawk_server.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_pacemaker_cluster_member.rb
chef/cookbooks/crowbar-pacemaker/recipes/role_pacemaker_remote.rb

This is used in role recipes to decide whether the role should be run or
not. This will allow us to stop rebuilding the run_list based on the
state of the nodes, since we move the logic in the role recipes.

chef: Use new CrowbarRoleRecipe.node_state_valid_for_role helper

---

crowbar_framework/app/models/pacemaker_service_object.rb

ChefObject.cloud_domain got moved to Crowbar::Settings.domain.
Needed because https://github.com/crowbar/crowbar-core/pull/519 was merged. Gating won't be green without https://github.com/crowbar/crowbar-openstack/pull/432

crowbar: Update for Crowbar::Settings.domain new API

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
crowbar_framework/app/models/pacemaker_service_object.rb

We have code in several locations that does this, and it feels better to
have a helper to not have too many copy & paste. It will also make it
easier to change the implementation of how IP assignments are stored.

crowbar, crowbar-pacemaker: Add helpers to fetch the VIP of a hostname

---

chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
crowbar_framework/app/models/pacemaker_service.rb

We do this instead of accessing attributes, in order to centralize the
location of the network definitions, so it can be changed.
Should go with https://github.com/crowbar/crowbar-core/pull/510

crowbar-pacemaker: Use Barclamp::Inventory.Network objects

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

The 'listen' command in haproxy configuration file no longer supports
setting the listening address right away. Instead it has to be put in a
'bind' command.
This change should be backwards compatible with previous haproxy
versions.

Updated haproxy cfg for version 1.6

---

chef/cookbooks/drbd/libraries/overview.rb
chef/cookbooks/drbd/providers/resource.rb

drbd-overview has changed in SP2 and it will not give us the previous "Unconfigured" status.
Now we need another way to find out when we want to execute `drbdadm -- --force create-md` for initialization.

Adapt to changes in drbd-overview

---

chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb
crowbar_framework/app/models/pacemaker_service.rb

node[:crowbar_ohai][:libvirt][:guestuuid] is maintained by crowbar's
ohai plugin to avoid the use of the architecture specific node[:dmi]
subtree.
Alternative to #143
Requires: crowbar/crowbar-core#677

Switch to node[:crowbar_ohai] for getting libvirt uuid

---

chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb

Our `corosync.conf.v2` template was based on a version from SLE HA which had some tunings accidentally dropped in the migration from SLE11.  In particular, some of the timeouts were too aggressive.
https://bugzilla.suse.com/show_bug.cgi?id=1001164

fix corosync.conf values (bsc#1001164)

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb

Until now, we were saving the sections as a default attribute, so that
they would be removed on every new run, resulting in the config being
regenerated from scratch. The downside of this is that all active roles
that use a loadbalancer resource must always be used in the chef run,
otherwise we lose part of the config. And this goes against our goal of
running only the strict minimal recipes when required.

haproxy: Make the sections for haproxy config persistent on each node

---

crowbar_framework/app/models/pacemaker_service.rb

It can happened that deployment["elements_expanded"][role_name]
can be nil. This will cause
"Failed to apply the proposal: exception before calling chef (undefined method `sort' for nil:NilClass)"

Fix undefined method `sort' for nil:NilClass

---

chef/cookbooks/drbd/providers/resource.rb

With 'ipaddress', it sometimes (??) uses the "public" IP instead... 
Specifically, after the upgrade, when running chef-client on SP2 node, and this results in having differnt IP's in the config of upgraded and non-upgraded node

Do not use node.ipaddress, but IP from the 'admin' range

---

crowbar_framework/app/models/api/pacemaker.rb

This is supposed to be called from `models/api/upgrade.rb` after the first node in cluster is upgraded.
So... the logic should be correct, but the question is if the method belongs in this place or elsewhere.
We could split it into pieces (like `cluster_for_node` etc.) and put them into PacemakerServiceObject, but that does not seem right as well, because we do not need the service object for anything.

Method for changing the cluster founder to given node

---

chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb

Our corosync.conf.v2 template was based on a version from SLE HA which
had some tunings accidentally dropped in the migration from SLE11.
In particular, some of the timeouts were too aggressive.
https://bugzilla.suse.com/show_bug.cgi?id=1001164
(cherry picked from commit c1d9c8f4e25e74a4cb5413b9f3e6337c7e1ff672)

[stable/3.0] fix corosync.conf values (bsc#1001164)

---

chef/cookbooks/pacemaker/Gemfile

It seems new versions requires a newer version of rack, that requires
ruby 2.2.2. See https://travis-ci.org/crowbar/crowbar-ha/jobs/142499249
(cherry picked from commit 5191cfd7dcac21df8e688d9429d59edefc75b1c0)

[3.0] pacemaker: Force use of old rack version

---

Gemfile

Rake 12.0.0 got released on Dec 6 but our rspec version still uses
removed code.
(cherry picked from commit d7dc20fe4be08348d6f85f3aa40588e8d10e6a65)

[3.0] travis: Use rake < 12.0.0

---

crowbar_framework/app/models/pacemaker_service.rb

It can happened that deployment["elements_expanded"][role_name]
can be nil. This will cause
"Failed to apply the proposal: exception before calling chef (undefined method `sort' for nil:NilClass)"

[3.0] Fix undefined method `sort' for nil:NilClass

---

chef/cookbooks/crowbar-pacemaker/recipes/attributes.rb
chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/cookbooks/crowbar-pacemaker/recipes/drbd.rb
chef/cookbooks/crowbar-pacemaker/recipes/drbd_setup.rb
chef/cookbooks/crowbar-pacemaker/recipes/openstack.rb
chef/cookbooks/crowbar-pacemaker/recipes/remote.rb
chef/cookbooks/crowbar-pacemaker/recipes/remote_attributes.rb
chef/cookbooks/crowbar-pacemaker/recipes/remote_delegator.rb

We make it possible to not run the crowbar-pacemaker cookbook when we run some OpenStack cookbook that use HA and require some specific setup (for drbd or haproxy, for instance).
This depends on and needs to be merged at the same time as: https://github.com/crowbar/crowbar-openstack/pull/635
Note: this includes a patch similar to https://github.com/crowbar/crowbar-ha/pull/116

Do not require crowbar-pacemaker cookbook to run when we configure HA in openstack

---

chef/cookbooks/crowbar-pacemaker/recipes/drbd_setup.rb
chef/cookbooks/drbd/providers/resource.rb
chef/cookbooks/drbd/resources/resource.rb

It should only be started by pacemaker (to avoid ownership conflict with
systemd), and therefore we should not require drbd to be running to do
the setup.
This is a followup of 52d11b7 and is required to properly fix
https://bugzilla.suse.com/show_bug.cgi?id=971771
(the three other commits are required to keep things working)

crowbar-pacemaker: Do not start or restart drbd service (bsc#971771)

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb

Return a commonly appropriate hash for the `meta` attribute of a `pacemaker_clone` resource.  This will allow us to remove a lot of duplication between identical `meta` attributes across many `pacemaker_clone` resources.
Original motivation comes from:
- https://bugzilla.suse.com/show_bug.cgi?id=965886

Add a helper for pacemaker_clone meta attributes (bsc#965886)

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb

New "done_os_upgrade" step identifies the situation when node
has been upgraded, but we still want to skip synchronization,
because other nodes in cluster may still have the old system.
It's introduced by https://github.com/crowbar/crowbar-core/pull/840

upgrade: Look for one more upgrade step when checking if node is being upgraded

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Right now, we end up with traces like this in syslog:
```
neutron-server[15962]: Traceback (most recent call last):
neutron-server[15962]: File "/usr/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
neutron-server[15962]: func(*args, **kwargs)
neutron-server[15962]: File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
neutron-server[15962]: proto.__init__(sock, address, self)
neutron-server[15962]: File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
neutron-server[15962]: self.handle()
neutron-server[15962]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
neutron-server[15962]: self.handle_one_request()
neutron-server[15962]: File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 330, …
```

haproxy: Fix server checks when ssl is used

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

This is useful to get info from haproxy, and to do some basic changes.

haproxy: Configure stats interface through unix sockets

---

crowbar_framework/app/models/api/pacemaker.rb

linked to https://github.com/crowbar/crowbar-core/pull/1155
this provides an error message that syncs the node with the actual error
in order to show it properly to the user on the error message

upgrade: Provide a better error

---

chef/cookbooks/pacemaker/libraries/pacemaker/cib_object.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/cib_object_spec.rb

**Still needs manual testing**
Fix a corner case where a remote primitive was incorrectly being reported as existing, due to `#crm_configure_show` returning a string like `node remote-d52-54-77-77-77-03:remote`, causing `#exists?` to return true.
This corner case arose during upgrade of a controller node, during `crowbar_join` after all primitives except for vips, drbd, and stonith resources were removed in anticipation of a switch to systemd agents.  At that point, the :update action of the remote primitive failed because it didn't know how to handle an object of type `node`, and this action happens before the containing transaction which would have recreated the primitive.
Since remote primitives use the `ocf:pacemaker:remote` agent, it probably makes sense to exclude them from this …

fix remote primitive existence test

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb
crowbar_framework/app/models/pacemaker_service.rb

If there are more addresses in the subnet, corosync could get
confused and not find correct address to bind to.
So let's try to use node's IP instead (our corosync.conf files are node specific anyway)
See https://bugzilla.suse.com/show_bug.cgi?id=1030437 for context.
~~This is not tested.~~ UPDATE: tested already few times.
I know that in that bug mentioned above there's a patch for corosync proposed, but i was hoping to maybe have a simpler one on our side.

Write node's IP address into corosync.conf instead of subnet

---

chef/cookbooks/drbd/providers/resource.rb
chef/cookbooks/drbd/templates/default/resource.erb
crowbar_framework/app/models/pacemaker_service.rb

Some of the failing mkcloud HA tests (e.g. [1])) have the following chef
failure:
Failure: (119) No valid meta-data signature found.
accompanied by an alert in the logs:
ambiguous node id: meta-data: 0, config: 1
This patch sets the node IDs explicitly in the resource config file as
recommended in this mailing list post[2] and documented for drbd
9.0[3] to attempt to prevent these meta-data errors. It also adds a
connection stanza as that may also be affecting drbd's ability to
generate metadata[4]. Protocol C indicates "Writes to the DRBD device
complete as soon as they have reached the local and all remote disks"
and is the protocol used in the example configuration file in the
documentation. We could consider making this configurable later.
[1] …

drbd: Set node-id in resource config

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb
crowbar_framework/app/models/pacemaker_service.rb

If there are more addresses in the subnet, corosync could get
confused and not find correct address to bind to.
So let's try to use node's IP instead.
See bsc#1030437 for context.
(cherry picked from commit de1dfc6fc99570126c53128a3a66380ce9e59f5b)
Forward-port of https://github.com/crowbar/crowbar-ha/pull/189

Write node's address into corosync.conf instead of subnet IP

---

crowbar_framework/app/models/pacemaker_service.rb

Since the logger parameter became optional for ServiceObjects[1],
deactivating a proposal has been broken, producing a cryptic error in
the UI:
wrong number of arguments (0 for 1)
This is because deactivating a proposal causes a lookup of proposal
dependencies which are no longer initialized with an argument[2], but
the pacemaker barclamp still requires this parameter. This patch
makes the pacemaker barclamp compatible with the new interface, though
more work will need to be done to clean up use of the logger parameter.
[1] https://github.com/crowbar/crowbar-core/pull/1025
[2] https://github.com/crowbar/crowbar-core/pull/1025/files#diff-494b2794304fa30be60cafd3d2c7f161

Make logger parameter optional

---

chef/cookbooks/drbd/providers/resource.rb

DRBD manual says "--force option replaces --overwrite-data-of-peer".
Although it was deprecated in 8.4 already, drbd startup started failing
only now when we switched to SLES12SP3.

drbd: Remove deprecated option for initial DRBD sync

---

crowbar_framework/app/models/pacemaker_service.rb

Also pass in the defined bmc_interface when configuring IPMI. Requires
crowbar-core #1260.
Co-Authored-By: Eugen Block <e.block@suse.com>

pacemaker: Use bmc_interface for IPMI (bsc#1046567)

---

crowbar_framework/app/models/pacemaker_service.rb

Also pass in the defined bmc_interface when configuring IPMI. Requires
crowbar-core #1260.
Co-Authored-By: Eugen Block <e.block@suse.com>
(cherry picked from commit c108bef064ebc17c5cca39aa775f5cbb8588ce8c)

[stable/4.0] pacemaker: Use bmc_interface for IPMI (bsc#1046567)

---

crowbar_framework/app/models/pacemaker_service.rb

In the IPMI barclamp, use_dhcp is set to true,
ignore_address_suggestions is irrelevant and the barclamp must use the
address discovered from the BMC interfaces. Since we're relying on dhcp
for this, we can't trust our database of allocated IPs to give us the
right address. This can cause the address for the STONITH device to be
either unset or incorrect, even when the IPMI barclamp reports the
correct BMC address. This patch looks up the use_dhcp value for the node
and, if set to true, uses the discovered address stored in the node
rather than the address allocated in the BMC network hash.

pacemaker: Use discovered BMC addr (bsc#1035215)

---

crowbar_framework/app/models/pacemaker_service.rb

In the IPMI barclamp, use_dhcp is set to true,
ignore_address_suggestions is irrelevant and the barclamp must use the
address discovered from the BMC interfaces. Since we're relying on dhcp
for this, we can't trust our database of allocated IPs to give us the
right address. This can cause the address for the STONITH device to be
either unset or incorrect, even when the IPMI barclamp reports the
correct BMC address. This patch looks up the use_dhcp value for the node
and, if set to true, uses the discovered address stored in the node
rather than the address allocated in the BMC network hash.
(cherry picked from commit f9603de719e834043d1701f96d86c5b6e718a59b)

[4.0] pacemaker: Use discovered BMC addr (bsc#1035215)

---

chef/cookbooks/crowbar-pacemaker/recipes/stonith.rb

In the IPMI barclamp, use_dhcp is set to true,
ignore_address_suggestions is irrelevant and the barclamp must use the
address discovered from the BMC interfaces. Since we're relying on dhcp
for this, we can't trust our database of allocated IPs to give us the
right address. This can cause the address for the STONITH device to be
either unset or incorrect, even when the IPMI barclamp reports the
correct BMC address. This patch looks up the use_dhcp value for the node
and, if set to true, uses the discovered address stored in the node
rather than the address allocated in the BMC network hash.
Note that this is not a direct cherry-pick, as the logic moved from the chef
recipe to the crowbar model between SOC6 and SOC7.

[3.0] pacemaker: Use discovered BMC addr (bsc#1035215)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

The check-ssl option does not seem to work properly as reported on
the mentioned bugs. Changing to the normal check option and leaving the ssl
check to the ssl-hello-chk option seems to make the checks work properly.
Tested extensively with different barclamps, options and ssl configs, this seems to work as expected for both SSL endpoints and normal ones.

haproxy: remove not working check-ssl option (bsc#1045783 bsc#1046093)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

The check-ssl option does not seem to work properly as reported on
the mentioned bugs. Changing to the normal check option and leaving the ssl
check to the ssl-hello-chk option seems to make the checks work properly
(cherry picked from commit d06fe9760db1a1fd8e47c4b4e161867ed90a27a6)

[4.0] haproxy: remove not working check-ssl option (bsc#1045783 bsc#1046093)

---

chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

This is the re-based version of #179 to see if tests fail
- We enable stickiness based on SSL sessions
- We add the ability to do stickiness based on cookies
- We allow to define the balance strategy on a per-resource basis
- We stop overriding the default balance strategy (and therefore use roundrobin by default)

Rework haproxy config for stickiness and balance strategy

---

chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb
chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

This is the backport of #208
We enable stickiness based on SSL sessions
We add the ability to do stickiness based on cookies
We allow to define the balance strategy on a per-resource basis
We stop overriding the default balance strategy (and therefore use roundrobin by default)

[4.0] Rework haproxy config for stickiness and balance strategy

---

chef/cookbooks/drbd/providers/resource.rb

DRBD manual says "--force option replaces --overwrite-data-of-peer".
Although it was deprecated in 8.4 already, drbd startup started failing
only now when we switched to SLES12SP3.
(cherry picked from commit e30972d339528cc56240a46315b84b8c103aa831)

[4.0] drbd: Remove deprecated option for initial DRBD sync

---

chef/data_bags/crowbar/migrate/pacemaker/100_stonith_in_rails.rb
crowbar_framework/app/controllers/pacemaker_controller.rb
crowbar_framework/app/models/pacemaker_service.rb

This commit continues the work which was done in
https://github.com/crowbar/crowbar-core/pull/1025. Which means we don't
have to pass the logger anymore.

service_object: Use rails logger directly

---

chef/cookbooks/pacemaker/recipes/default.rb

~~[no manual testing yet]~~ Manually tested (albeit on Cloud 6) and seems to work fine (see [bsc#978010](https://bugzilla.suse.com/show_bug.cgi?id=978010))
Pacemaker has a problem with old-style LSB init scripts on SLE12.  This is because when invoking an action such as `start` or `stop` on these init scripts, they first source `/etc/rc.status`, which causes a redirect to `systemctl`, which finally invokes the init script again, this time with `SYSTEMD_NO_WRAP` set.
So when we define an `lsb:*` primitive resource inside Pacemaker, the result is that when it starts the service, systemd thinks that *it* started the service and is therefore its owner and hence responsible for shutting it down when the system is being shut down.  This can have disastrous results - for example on system …

prevent systemd from owning Pacemaker-controlled services (bsc#980341)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

'backup' means that given server is only used in load
balancing when all other non-backup servers are unavailable.
We might need a setup (e.g. with mariadb cluster) where we want
to prevent existence of multiple servers being accessed at the same time.

Add a support to use 'backup' option in server line.

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

'backup' means that given server is only used in load
balancing when all other non-backup servers are unavailable.
'stick on dst' should make sure that destination server is not
left even if it is backup one and non-backup is healthy again.
This should prevent additional disruption once the failing node
is back and running.
We might need a setup (e.g. with mariadb cluster) where we want
to prevent existence of multiple servers being accessed at the same time.
(cherry picked from commit c1cf765bb38932ed5747e749ebf5341846094dd7)
Backport of https://github.com/crowbar/crowbar-ha/pull/215

[stable/4.0] Add a support to use 'backup' option in server line.

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

fastinter/rise/fall values influence haproxy monitoring behavior.
See e.g. https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-to-set-up-mysql-load-balancing--3

Allow configuration of more options for server lines.

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Following on from PR #220, improve the code readability of the server
options. This change places the logic in a clear position before
spitting it out into the server line.

A quick tidy up of haproxy server options

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

inter/fastinter/rise/fall values influence haproxy monitoring behavior.
See e.g. https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-to-set-up-mysql-load-balancing--3
(cherry picked from commit 3d539648c477f957340e74c8daa6596b688fa976)
Backport of https://github.com/crowbar/crowbar-ha/pull/220

[4.0] Allow configuration of more options for server lines.

---

chef/cookbooks/crowbar-pacemaker/providers/service.rb

The 1st commit is just a pretty simple fix for `service_is_running?` to make it work with Master/Slave resources.
The 2nd commit enhances the pacemaker "service" provider to allow passing in alternative start/stop commands when used with the "restart_crm_resource" flag. We need this for the galera resource agent. In order to restart mysql on a single node we need to get the resource though a demote/promote cycle once (instead of start/stop). See e.g. https://github.com/jhesketh/crowbar-openstack/commit/ce00239fe10848b591a561a16d28a43d7f68a5a7 for the current work in progress.

crowbar-pacemaker: Allow overriding start/stop commands for crm_resource

---

chef/cookbooks/haproxy/files/default/haproxy.service.override.conf
chef/cookbooks/haproxy/recipes/setup.rb

It's possible that haproxy is unable to close open connections during
restart action so we make sure systemd kills it before we hit pacemaker
service timeout that would ultimately fence the haproxy node (bsc#1056371).

haproxy: Make sure that systemd kills haproxy service on restart

---

chef/cookbooks/pacemaker/libraries/pacemaker/cib_object.rb
chef/cookbooks/pacemaker/spec/helpers/non_runnable_resource.rb
chef/cookbooks/pacemaker/spec/helpers/runnable_resource.rb

Sometimes reconfiguring existing resources (e.g. groups) in the cluster
will trigger some resources of the cluster being moved and/or restarted.
Use --wait to block until the transition has finished and the cluster
has settled. This helps to avoid race issues e.g. when pacemaker needs
to restart resources after new resource is added to an existing group.

pacemaker: Use --wait with crm configure command

---

chef/cookbooks/haproxy/files/default/haproxy.service.override.conf
chef/cookbooks/haproxy/recipes/setup.rb

It's possible that haproxy is unable to close open connections during
restart action so we make sure systemd kills it before we hit pacemaker
service timeout that would ultimately fence the haproxy node (bsc#1056371).
(cherry picked from commit 4e4c6e2138bb765165e938dce132c79e4e4de56b)

[4.0] haproxy: Make sure that systemd kills haproxy service on restart

---

chef/cookbooks/haproxy/attributes/default.rb
chef/cookbooks/haproxy/files/default/429.http
chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/recipes/setup.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Provides a new option on the loadbalancer resource to allow for rate
limiting per frontend. A integer values is passed and it signifies the
maximum request per minute from an IP.
Also provides a custom 429 error file for haproxy to server when the
rate limit is hit, so clients receive the proper response
Based on the code from https://github.com/sap-oc/crowbar-openstack/issues/21

haproxy: provide a option to ratelimit frontends

---

chef/cookbooks/pacemaker/libraries/pacemaker/cib_object.rb
chef/cookbooks/pacemaker/spec/helpers/non_runnable_resource.rb
chef/cookbooks/pacemaker/spec/helpers/runnable_resource.rb

Sometimes reconfiguring existing resources (e.g. groups) in the cluster
will trigger some resources of the cluster being moved and/or restarted.
Use --wait to block until the transition has finished and the cluster
has settled. This helps to avoid race issues e.g. when pacemaker needs
to restart resources after new resource is added to an existing group.
(cherry picked from commit 908a7743a6dffd627423508d7af9d7d3d5c47a13)

[4.0] pacemaker: Use --wait with crm configure command

---

chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb

When remote nodes are present (in a Compute HA setup) we want to avoid
the VIPs being started on the remote pacemaker nodes. Usually this is
taken care of by a location constraint on the haproxy group. However, if
a VIP is added to the node after the initial deployment. The creation of
the VIP resource and the update of the group happen as to separate
operations on the cluster. In that case it might be that the cluster
tries to launch the VIP on one of the remote nodes first. With the
commit we add the usual "controller_only_location" location constraint
directly on the VIP to avoid that. Note: The location constraint is
somewhat redundant after the haproxy group is updated, but it shouldn't
do any harm.
This is a follow up on: 58093f6f510c1e5697cb6b80cefc5a3a4e1bf55d

haproxy: Add location contraint to VIP directly

---

crowbar_framework/app/models/pacemaker_service.rb

**NOTE: this requires https://github.com/crowbar/crowbar-core/pull/1326 to be merged first **
If IPMI barclamp is configured to not modify IPMI settings, Pacemaker
should use discovered IP just like in DHCP mode.

ipmi: Use discovered IP in read-only mode

---

chef/cookbooks/haproxy/attributes/default.rb
chef/cookbooks/haproxy/files/default/429.http
chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/recipes/setup.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Provides a new option on the loadbalancer resource to allow for rate
limiting per frontend. A integer values is passed and it signifies the
maximum request per minute from an IP.
Also provides a custom 429 error file for haproxy to server when the
rate limit is hit, so clients receive the proper response
(cherry picked from commit c0994c189d5df1f62f8f0d2462d46ad8dc826528)

[4.0] haproxy: provide a option to ratelimit frontends

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
chef/data_bags/crowbar/migrate/pacemaker/200_clone_stateless_services.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
crowbar_framework/config/locales/pacemaker/en.yml

Pacemaker is not strictly required for stateless active/active services,
since orchestration, fencing, and so on is not necessarily useful in
that case.
Enabling this option does simplify the setup in the OpenStack case quite
significantly, but comes with a cost, like pacemaker not restarting
services that have failed.

pacemaker: Add option to not manage stateless active/active services

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
chef/cookbooks/pacemaker/spec/fixtures/keystone_primitive.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource/primitive_spec.rb

The parser for the "op" part of a resource definition was missing the
"promote" and "demote" operations. This was never noticed up to now as
we didn't use them until we introduced galera support in the database
barclamp. This bug caused calls to "crm config" in every chef-client run
for resources that contain custom settings for the "promote" or "demote"
operation.

pacemaker: Add missing  operations to the parser

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
chef/cookbooks/pacemaker/spec/fixtures/keystone_primitive.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource/primitive_spec.rb

The parser for the "op" part of a resource definition was missing the
"promote" and "demote" operations. This was never noticed up to now as
we didn't use them until we introduced galera support in the database
barclamp. This bug caused calls to "crm config" in every chef-client run
for resources that contain custom settings for the "promote" or "demote"
operation.
(cherry picked from commit eda7fc9cde8a46c5109408a518dcf289e0857bda)
Backport of https://github.com/crowbar/crowbar-ha/pull/241

[4.0] pacemaker: Add missing  operations to the parser

---

crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml

clone_stateless_services_hint_html is required by _edit_attributes.html.haml
Introduced by https://github.com/crowbar/crowbar-ha/pull/238

Fix the translation label

---

chef/cookbooks/crowbar-pacemaker/libraries/cibattribute.rb

We forgot to redirect stdout and sterr for #cib_up_for_node?, making the
logs be full of 1s and 0s.
This redirects all the output of the command to /dev/null to avoid
filling up the logs with unwanted lines

crowbar-pacemaker: hide output for #cib_up_for_node?

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
chef/cookbooks/hawk/metadata.rb
chef/cookbooks/hawk/recipes/server.rb

**crowbar-pacemaker: Update apache override for systemd restart LWRP**
We don't want systemd and pacemaker to handle restart of apache2 at the
same time, so override the action for the utils_systemd_service_restart
LWRP.
**hawk: Make systemd restart hawk service on failures**
This offers some automatic recovery, which is nice.

Use new utils_systemd_service_restart LWRP

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
chef/data_bags/crowbar/migrate/pacemaker/101_clone_stateless_services.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
crowbar_framework/config/locales/pacemaker/en.yml

Pacemaker is not strictly required for stateless active/active services,
since orchestration, fencing, and so on is not necessarily useful in
that case.
Disabling this option does simplify the setup in the OpenStack case quite
significantly, but comes with a cost, like pacemaker not restarting
services that have failed.
The default is to keep the same behavior as in the past. This may change
when we implement Restart= for systemd services and if it found that
this approach has no negative impact.
(cherry picked from commit ada1d41565c6a08a3d499f141fae7cb5c45fd052)
Backport of https://github.com/crowbar/crowbar-ha/pull/238

[4.0] pacemaker: Add option to stop managing stateless active/active services

---

chef/cookbooks/crowbar-pacemaker/libraries/cibattribute.rb

We forgot to redirect stdout and sterr for #cib_up_for_node?, making the
logs be full of 1s and 0s.
This redirects all the output of the command to /dev/null to avoid
filling up the logs with unwanted lines
(cherry picked from commit 464d727ade1e40e8999563c3895a23dafc6d8c57)
Backport of https://github.com/crowbar/crowbar-ha/pull/250

[4.0] crowbar-pacemaker: hide output for #cib_up_for_node?

---

chef/cookbooks/crowbar-pacemaker/recipes/apache.rb
chef/cookbooks/hawk/metadata.rb
chef/cookbooks/hawk/recipes/server.rb

**crowbar-pacemaker: Update apache override for systemd restart LWRP**
We don't want systemd and pacemaker to handle restart of apache2 at the
same time, so override the action for the utils_systemd_service_restart
LWRP.
**hawk: Make systemd restart hawk service on failures**
This offers some automatic recovery, which is nice.
Depends on https://github.com/crowbar/crowbar-core/pull/1332
Backport of https://github.com/crowbar/crowbar-ha/pull/244

[4.0] Use new utils_systemd_service_restart LWRP

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

This allows defaults for each server to be set (such as inter etc).
This will simplify common params for servers such as monitoring
details.

Allow default-server options to be set in haproxy

---

chef/cookbooks/pacemaker/attributes/default.rb
chef/cookbooks/pacemaker/recipes/setup.rb
chef/cookbooks/pacemaker/templates/default/crm-initial.conf.erb
chef/data_bags/crowbar/migrate/pacemaker/201_migration_threshold.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema

Provides a new way to configure pacemaker migrate-threshold option
per frontent. An integer value is passed and it signifies the maximun
numbers of retries before migrate a service to other node. Its value
is 3 by default.

pacemaker: provide a option to configure migrate-threshold

---

chef/cookbooks/corosync/attributes/default.rb
chef/cookbooks/corosync/recipes/config.rb
chef/cookbooks/corosync/recipes/firewall.rb
chef/cookbooks/corosync/templates/default/corosync.conf.erb
chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb
chef/cookbooks/corosync/templates/default/firewall.erb
chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/data_bags/crowbar/migrate/pacemaker/201_add_ring_array.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
crowbar_framework/app/models/pacemaker_service.rb
crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
crowbar_framework/config/locales/pacemaker/en.yml

Customer has requested the ability to configure an additional corosync
ring to "fully leverage the second bond in their dual bond environment".
The pacemaker cluster nodes will have visibility of one another over
both bonds and, when a failure occurs on the first bond, a cluster
failure will be averted due to the existence of the second ring over
the second bond.
In order to accomplish this, the flat list of single ring attributes
and web UI form fields is replaced by an array and _**n**_ number of web UI
form fields to support _**n**_ number of rings. The UI and validation code
restrict the maximum number of rings to 2. If there is ever a need for
for more rings, simply search for '2', 'two', and 'second' and make
the appropriate changes.

Add support for multiple Corosync rings

---

chef/cookbooks/pacemaker/attributes/default.rb
chef/cookbooks/pacemaker/recipes/setup.rb
chef/cookbooks/pacemaker/templates/default/crm-initial.conf.erb
chef/data_bags/crowbar/migrate/pacemaker/102_migration_threshold.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema

Provides a new way to configure pacemaker migrate-threshold option
per frontent. An integer value is passed and it signifies the maximun
numbers of retries before migrate a service to other node. Its value
is 3 by default.
(cherry picked from commit 97794fdc8d4a5350f52d163d14b0f374ef99c50e)
Backport of https://github.com/crowbar/crowbar-ha/pull/261

[4.0] pacemaker: provide a option to configure migrate-threshold

---

chef/cookbooks/corosync/attributes/default.rb
chef/cookbooks/corosync/recipes/config.rb
chef/cookbooks/corosync/recipes/firewall.rb
chef/cookbooks/corosync/templates/default/corosync.conf.erb
chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb
chef/cookbooks/corosync/templates/default/firewall.erb
chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/data_bags/crowbar/migrate/pacemaker/102_add_ring_array.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
crowbar_framework/app/models/pacemaker_service.rb
crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
crowbar_framework/config/locales/pacemaker/en.yml

Customer has requested the ability to configure an additional corosync
ring to "fully leverage the second bond in their dual bond environment".
The pacemaker cluster nodes will have visibility of one another over
both bonds and, when a failure occurs on the first bond, a cluster
failure will be averted due to the existence of the second ring over
the second bond.
In order to accomplish this, the flat list of single ring attributes
and web UI form fields is replaced by an array and _**n**_ number of web UI
form fields to support _**n**_ number of rings. The UI and validation code
restrict the maximum number of rings to 2. If there is ever a need for
for more rings, simply search for '2', 'two', and 'second' and make
the appropriate changes.
Backport-of: …

[4.0] Add support for multiple Corosync rings

---

chef/cookbooks/crowbar-pacemaker/metadata.rb

recommends and suggests are useless in the metadata files as they dont
do anything and are deprecated[0]
[0] https://chef.github.io/chef-rfc/rfc085-remove-unused-metadata.html

crowbar-framework: remove useless metadata

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb

Up to now we only reset the synchronisation marks for the founder node
when re-applying a barlcamp. The reset needs to happen for all nodes of
a cluster. Otherwise we will run into synchronisation issues if e.g. the
first deployment of a barclamp fails and all nodes except of the founder
still have the sync marks set.

crowbar-pacemaker: Reset sync-marks for all nodes

---

chef/cookbooks/drbd/templates/default/resource.erb

https://bugzilla.suse.com/show_bug.cgi?id=1036603
There were several cases where DRBD replication went out of sync
without good reason. In that state, postgresql still worked on the primary
but could not be migrated to the secondary.
As documented in http://docs.linbit.com/docs/users-guide-9.0/#s-configure-split-brain-behavior
DRBD comes with builtin handling of split-brain scenarios,
where certain safe cases can be resolved automatically, such as
one node having zero changes compared to the other.

drbd: enable autorecovery after split-brain (bsc#1036603)

---

chef/cookbooks/corosync/attributes/default.rb

The default attributes are getting merged with the default from the
crowbar barclamp proposal, rather than overwritten, so we always
have two entries, one broken one. For upgraded installs this is
basically desastrously breaking the install, as found out in a live
demo. All debugging thanks to Adam.

corosync: remove nonsensical ring default

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

After a cowbar-ha update, the 'stick' attribute introduced in
PR #208 is missing from the existing node[:haproxy][sections]
entries, which may result in errors such as:
```
Chef::Mixin::Template::TemplateError
------------------------------------
undefined method `[]' for nil:NilClass
```
This PR adds checks for the existence of the 'stick' attribute
before dereferencing it.

haproxy: Check for existance of "content[:stick]" (bsc#1062889)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

(backports #258)
After a cowbar-ha update, the 'stick' attribute introduced in PR #209 is missing from the existing `node[:haproxy][sections]` entries, which may result in errors such as:
```
Chef::Mixin::Template::TemplateError
------------------------------------
undefined method `[]' for nil:NilClass
```
This PR adds checks for the existence of the 'stick' attribute before dereferencing it.
Fixes [bsc#1062889](https://bugzilla.suse.com/show_bug.cgi?id=1062889).

[4.0] haproxy: Check for existence of "content[:stick]"

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

This allows defaults for each server to be set (such as inter etc).
This will simplify common params for servers such as monitoring
details.
(cherry picked from commit 8ac75cf6d3db958997e47e62b79e14b400fe1131)
Backport of https://github.com/crowbar/crowbar-ha/pull/242

[4.0] Allow default-server options to be set in haproxy

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb

When flatting out the list of 'op' parameters in pacemaker primitive
resource, that list can be nil instead of empty. This change addresses
that situation.

pacemaker: deal with nil op attributes

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb

Backport from https://github.com/crowbar/crowbar-ha/pull/280
When flatting out the list of 'op' parameters in pacemaker primitive
resource, that list can be nil instead of empty. This change addresses
that situation.

[4.0] pacemaker: deal with nil op attributes

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource.rb
chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
chef/cookbooks/pacemaker/spec/fixtures/keystone_primitive.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource/primitive_spec.rb
chef/cookbooks/pacemaker/spec/providers/primitive_spec.rb

It turns out that we can have multiple entries for the same data type.
For instance, when using ms, we need to define multiple "op monitor"
with different roles:
https://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/_monitoring_multi_state_resources.html
Also, add support for missing op operations (notify will be used).

pacemaker: Allow having multiple op settings for master/slave

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource.rb
chef/cookbooks/pacemaker/libraries/pacemaker/resource/primitive.rb
chef/cookbooks/pacemaker/spec/fixtures/keystone_primitive.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource/primitive_spec.rb
chef/cookbooks/pacemaker/spec/providers/primitive_spec.rb

It turns out that we can have multiple entries for the same data type.
For instance, when using ms, we need to define multiple "op monitor"
with different roles:
https://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/_monitoring_multi_state_resources.html
Also, add support for missing op operations (notify will be used).
Backport of https://github.com/crowbar/crowbar-ha/pull/282

[4.0] pacemaker: Allow having multiple op settings for master/slave

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb

Authorized keys need to be deployed to nodes before joining cluster
so that the founder can ssh to the new node from alert handler.
Requires https://github.com/crowbar/crowbar-core/pull/1451

crowbar-pacemaker: Deploy ssh keys before joining

---

chef/cookbooks/pacemaker/libraries/pacemaker/alert.rb
chef/cookbooks/pacemaker/providers/alert.rb
chef/cookbooks/pacemaker/resources/alert.rb
chef/cookbooks/pacemaker/spec/fixtures/alert.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/alert_spec.rb
chef/cookbooks/pacemaker/spec/providers/alert_spec.rb

Pacemaker supports alert feature which can be used to attach scripts
to various cluster events. This commit exposes basic alerts to chef as
resources. Creating, updating and deleting is supported.

pacemaker: Alert resource

---

chef/cookbooks/pacemaker/libraries/pacemaker/alert.rb
chef/cookbooks/pacemaker/spec/fixtures/alert.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/alert_spec.rb
chef/cookbooks/pacemaker/spec/providers/alert_spec.rb

The receiver/recipient of alerts is not mandatory. Modified wrapper classes to support such cases.

pacemaker: Made alert receiver optional

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

It seems at least on the concurrent Galera DB connection side we
can easily hit the default limit of 2000 parallel connections. Raise
it to the global connection limit.

haproxy: make maxconn parameter configurable (bsc#1068962)

---

chef/cookbooks/pacemaker/attributes/default.rb

to make it longer than the 90s that systemd is waiting
before it sends a SIGKILL to a stuck service.
This can help to avoid needless random fencing of nodes during shutdown/reboot
https://bugzilla.suse.com/show_bug.cgi?id=1056473

Increase pacemaker timeout to 120 (bsc#1056473)

---

chef/cookbooks/pacemaker/attributes/default.rb

to make it longer than the 90s that systemd is waiting
before it sends a SIGKILL to a stuck service.
This can avoid needless random fencing of nodes during shutdown/reboot
https://bugzilla.suse.com/show_bug.cgi?id=1056473
(cherry picked from commit 2502d1e2929d5db151b7ebd0181429891eaee298)
Backport of #227

pacemaker: Increase pacemaker timeout to 120 (bsc#1056473)

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb

Authorized keys need to be deployed to nodes before joining cluster
so that the founder can ssh to the new node from alert handler.
(cherry picked from commit 6d4b0667f7f3f2cd48a4b6735c8f84e1c0368c7d)
backport of #285 
requires https://github.com/crowbar/crowbar-core/pull/1457

[4.0] crowbar-pacemaker: Deploy ssh keys before joining

---

crowbar_framework/app/models/api/pacemaker.rb

When we introduced the new syncmarks for pacemaker
the founder was changed from a boolean indicating
that the node is a founder, to the fqdn of the founder
This results into #set_node_as_founder not working as expected
and unable to find the founder and change it to a new founder
properly
This patch refactors #set_node_as_founder to make sure we
set the new founder in the proper role for this cluster and
we set the drbd master (if exists) to the new_founder
(cherry picked from commit 7be1e3fc8ebaeca5c6ad1a5df4c1765801904c19)
Forward-port-of: https://github.com/crowbar/crowbar-ha/pull/291

upgrade: fix pacemaker founder searchs

---

chef/data_bags/crowbar/template-pacemaker.json

As a reminder, with this option set to false, pacemaker will not manage
stateless services such as OpenStack API services -- instead, systemd
will restart them on crash.
This works rather well, and since we never went to the point where we
had some OCF resource agent for such services, and only use a systemd
resource agent, the benefit of pacemaker is too limited. Reducing
complexity, and converging with the Ardana deployment is therefore more
interesting here.

pacemaker: Change default for clone_stateless_services to false

---

chef/cookbooks/pacemaker/providers/primitive.rb
chef/data_bags/crowbar/migrate/pacemaker/203_op_defaults.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema

**Note:** this is a rework from https://github.com/crowbar/crowbar-ha/pull/262
We needed to add a default option for the pacemaker op defaults. In
particular we are interested in offering a default for "op monitor
on-fail" action.
Pacemaker does not offer a configuration option to offer such defaults
for all resources. There's a way to do it for a single resource with
rsc_defaults, but that is not our case. Also with Pacemaker you could
link one resource operations to another one with 'id-ref', but in that
case if you modify the reference resource it will cascade changes to all
other resourced.
This approach allows to store in the pacemaker barclamp a default for
op. In this case we are only interested in op monitor but could easily
be extended later on.
The primitive will read that value …

pacemaker: added support for op defaults

---

crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
crowbar_framework/app/models/pacemaker_service.rb
crowbar_framework/app/views/barclamp/pacemaker/_edit_attributes.html.haml
crowbar_framework/config/locales/pacemaker/en.yml

DRBD is only useful for PostgreSQL HA and unclustered RabbitMQ HA, which
are both features we want to disallow for new deployments. So DRBD has
no real use in new deployments.
Depends on https://github.com/crowbar/crowbar-openstack/pull/1545

Disallow DRBD for new deployments

---

chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb
chef/cookbooks/pacemaker/attributes/default.rb
crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js

This fixes https://bugzilla.suse.com/show_bug.cgi?id=981056
On pacemaker clusters of 2-nodes, we should set the
corosync quorum conf to use `two_node: 1` rather than
force the use of `no-quorum-policy=ignore` in pacemaker.
The corosync `two_nodes:1` tells corosync that it only
needs 1 vote for quorum instead of 2.
Before this patch we'd force these clusters to use the ignore
policy when the cluster was being defined via the
crowbar web ui (via javascript) which lead to
bugs like https://bugzilla.suse.com/show_bug.cgi?id=981056.
This patch is removing the javascript function that is
enforcing this behaviour completely as now that 2-node
clusters behave as expected, users should get a choice in
what no-quorum-policy they want to use.

2-node clusters should have two_node: 1

---

chef/cookbooks/pacemaker/providers/primitive.rb
chef/data_bags/crowbar/migrate/pacemaker/105_op_defaults.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema

backport of https://github.com/crowbar/crowbar-ha/pull/297
We needed to add a default option for the pacemaker op defaults. In
particular we are interested in offering a default for "op monitor
on-fail" action.
Pacemaker does not offer a configuration option to offer such defaults
for all resources. There's a way to do it for a single resource with
rsc_defaults, but that is not our case. Also with Pacemaker you could
link one resource operations to another one with 'id-ref', but in that
case if you modify the reference resource it will cascade changes to all
other resourced.
This approach allows to store in the pacemaker barclamp a default for
op. In this case we are only interested in op monitor but could easily
be extended later on.
The primitive will read that value from the founder …

[4.0] pacemaker: added support for op defaults

---

chef/cookbooks/corosync/recipes/config.rb
chef/cookbooks/pacemaker/recipes/default.rb
chef/cookbooks/pacemaker/spec/helpers/provider.rb
crowbar_framework/app/models/pacemaker_service.rb

When a new node is added to the cluster, waiting for corosync reload after the end of chef-client run (:delayed action) is too late.
With current implementation of pacemaker sync marks, crm_attribute calls are used and they fail when corosync does not have the full information about all its nodes. So we must somehow extend the first synchronization that happens before the sync marks mechanism is used.
~Alternative solution to https://github.com/crowbar/crowbar-ha/pull/303 , this one looks cleaner~
Also required for adding cluster node: https://github.com/crowbar/crowbar-openstack/pull/1583

Update corosync configuration correctly and in time when adding a new cluster node

---

chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb
chef/cookbooks/pacemaker/attributes/default.rb
crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js

This fixes https://bugzilla.suse.com/show_bug.cgi?id=981056
On pacemaker clusters of 2-nodes, we should set the
corosync quorum conf to use `two_node: 1` rather than
force the use of `no-quorum-policy=ignore` in pacemaker.
The corosync `two_nodes:1` tells corosync that it only
needs 1 vote for quorum instead of 2.
Before this patch we'd force these clusters to use the ignore
policy when the cluster was being defined via the
crowbar web ui (via javascript) which lead to
bugs like https://bugzilla.suse.com/show_bug.cgi?id=981056.
This patch is also updates the javascript function that is
enforcing this behaviour to only force `no-quorum-policy=ignore`
on 1 node clusters. As now 2-node clusters behave as expected.
Finally this changes the default `no-quorum-policy` in the chef
pacemaker …

[4.0] pacemaker: 2-node clusters should have two_node: 1 (bsc#1023981)

---

chef/cookbooks/pacemaker/libraries/pacemaker/resource.rb
chef/cookbooks/pacemaker/spec/libraries/pacemaker/resource_spec.rb

Based on 4e944918b7df65a25b8737c41ba5ee5558f9c6f1.
There is the chance that multiple 'meta' parameters appear in
a CIB resource. This produce an exception in 'extract_hash`
method.
For example, in bsc#1093898 a client provide a crm configuration
with this layout:
```
primitive neutron-ha-tool ocf:openstack:neutron-ha-tool \
params os_auth_url="http://cluster-Controllerha.cloud.orange:5000/v2.0/" os_insecure=false os_region_name=RegionOne os_tenant_name=admin os_username=admin \
op monitor interval=10s \
op start interval=0 timeout=1800s \
meta target-role=Started \
meta maintenance=false
```
This patch allows multiple 'meta' parameter in the result.
(cherry picked from commit bd7c014c6dc7811fba959e7fe880365310d359c1)

[4.0] pacemaker: allow multiple meta parameters (bsc#1093898)

---

chef/cookbooks/crowbar-pacemaker/providers/drbd_create_internal.rb

When a node is reinstalled the DRBD resources don't are configured
because of the node attribute drbd.rsc.<resource_name>.configured
is marked as true, and the setup is skiped.
This solution store a counter instead of true and false. In each
reinstalation this counter is increased by crowbar. So checking
if the current reinstalation number is equal to the configured
stored in the node attributes it can skip when it's necesary
and setup the DRBD resources when it's needed.

[4.0] DRBD: fix when reinstall node

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

We found that SSL stick tables in haproxy can get full on big
deployments. We are increasing the stick table from 30k to 100k, which
is also the size the other stick tables have.

haproxy: increased SSL stick table to 100k

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Backport of https://github.com/crowbar/crowbar-ha/pull/313 to SOC7.
We found that SSL stick tables in haproxy can get full on big
deployments. We are increasing the stick table from 30k to 100k, which
is also the size the other stick tables have.
(cherry picked from commit ba7e51a4d63316b1b01a5aad3d8a0749753bc5f2)

[4.0] haproxy: increased SSL stick table to 100k

---

chef/cookbooks/pacemaker/recipes/default.rb

If the cluster has (say) 3 corosync nodes and 2 remote nodes, `crm_mon` will display:
5 nodes configured
Previously this check was always failing with remote nodes, because it was only taking into account the corosync nodes, so it was expecting it to say:
3 nodes configured.

Fix Pacemaker cluster online check

---

chef/data_bags/crowbar/migrate/pacemaker/106_allow_larger_cluster.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/models/pacemaker_service.rb

Currently, DRBD enabled clusters are forced to be only two nodes. To
fascitate upgrades from SOC7 to Cloud 8, we need to switching from
PostgreSQL to MariaDB with Galera, which requires three node clusters at
a minimum.

[4.0] drbd: Add switch to short circuit cluster size check

---

chef/cookbooks/pacemaker/recipes/setup.rb

The schema version is a multi digit number that shouldn't be
compared as a string, because otherwise "2.10" < "2.9".

pacemaker: Fix version comparsion on cib schema

---

chef/cookbooks/crowbar-pacemaker/libraries/helpers.rb
chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/data_bags/crowbar/migrate/pacemaker/107_populate_drbd_nodes.rb
chef/data_bags/crowbar/template-pacemaker.json
chef/data_bags/crowbar/template-pacemaker.schema
crowbar_framework/app/models/pacemaker_service.rb

We have to allow user to add a new node into 2-node DRBD cluster, so that such cluster can hold (3-node) galera configuration later.
But as (our version of) DRBD needs exactly 2 nodes, there are some tweaks necessary so that the extra node does not have DRBD configured, although it is part of the pacemaker cluster.

Adding a node into DRBD cluster

---

chef/data_bags/crowbar/migrate/pacemaker/300_noop.rb
chef/data_bags/crowbar/template-pacemaker.json

To give some head room for future schema migrations in the
stable/5.0-pike branch we bump the schema revision for all barclamps to
300. The migration itself is a noop it's just there to ensure the
schema-revision is increased on all existing proposals and roles (mainly
needed for future upgrades from stable/5.0-pike).

Bump schema revision to 300 after release

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

Disable SSLv3 and TLS1.0 and set the DH parameters nicely
so that we don't use weak DH. Also reduce the default ciphers
to the SUSE recommended defaults. None of that is raelly effective
yet in mode tcp though which we use by default.

haproxy: use secure defaults

---

crowbar_framework/app/models/api/pacemaker.rb

It could end badly if we proceed with the upgrade while some node
is in maintenance state (stopping corosync on such node might lead
to pacemaker's confusion about the services running there).
So let's add a specific check that is executed before the upgrade
and which does not allow user to upgrade such setup.

[4.0] upgrade: Add a healthcheck for pacemaker node state

---

crowbar_framework/app/models/api/pacemaker.rb

It could end badly if we proceed with the upgrade while some node
is in maintenance state (stopping corosync on such node might lead
to pacemaker's confusion about the services running there).
So let's add a specific check that is executed before the upgrade
and which does not allow user to upgrade such setup.
(cherry picked from commit 851b73b1d642438b7ed1bab030b3262151b6f705)
Port of https://github.com/crowbar/crowbar-ha/pull/331

[5.0] upgrade: Add a healthcheck for pacemaker nodes state

---

chef/cookbooks/pacemaker/recipes/default.rb

Backport of #174 to SOC7.
Pacemaker has a problem with old-style LSB init scripts on SLE12.  This is because when invoking an action such as `start` or `stop` on these init scripts, they first source `/etc/rc.status`, which causes a redirect to `systemctl`, which finally invokes the init script again, this time with `SYSTEMD_NO_WRAP` set.
So when we define an `lsb:*` primitive resource inside Pacemaker, the result is that when it starts the service, systemd thinks that *it* started the service and is therefore its owner and hence responsible for shutting it down when the system is being shut down.  This can have disastrous results - for example on system shutdown, systemd might try to stop drbd before or in parallel with other services such as Pacemaker which would have stopped it cleanly …

[4.0] prevent systemd from owning Pacemaker-controlled services (bsc#980341)

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/cookbooks/pacemaker/recipes/default.rb
crowbar_framework/app/models/pacemaker_service.rb

If newly added node is fast and goes ahead of the founder it can hit the first
syncmark before cluster is fully configured. Added flag enables conditional timeout
extension for new nodes while keeping old timeout during initial deployment.

pacemaker: Wait more for cluster to be online

---

chef/data_bags/crowbar/migrate/pacemaker/204_remove_allow_larger_cluster.rb
chef/data_bags/crowbar/template-pacemaker.json

In the 4.0 branch with schema revision 106 we introduced the
["drbd"]["allow_larger_cluster"] attribute. That attribute is only
needed in 4.0 and was never forward ported to 5.0. So this needs to
be cleaned up during the upgrade from 4.0 to 5.0

[5.0] pacemaker: Cleanup 4.0 specific attribute

---

crowbar_framework/app/models/api/pacemaker.rb

It could end badly if we proceed with the upgrade while some node
is in maintenance state (stopping corosync on such node might lead
to pacemaker's confusion about the services running there).
So let's add a specific check that is executed before the upgrade
and which does not allow user to upgrade such setup.
(cherry picked from commit 851b73b1d642438b7ed1bab030b3262151b6f705)
Port of https://github.com/crowbar/crowbar-ha/pull/331

upgrade: Add a healthcheck for pacemaker nodes state

---

chef/cookbooks/crowbar-pacemaker/recipes/default.rb
chef/cookbooks/pacemaker/recipes/default.rb
crowbar_framework/app/models/pacemaker_service.rb

If newly added node is fast and goes ahead of the founder it can hit the first
syncmark before cluster is fully configured. Added flag enables conditional timeout
extension for new nodes while keeping old timeout during initial deployment.
(cherry picked from commit 655ae273723a5500d9336544fe71681a5afcd412)
forward port of #335

[5.0] pacemaker: Wait more for cluster to be online

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix by limiting bunlder version to be less
than 2.0.0:
https://github.com/travis-ci/travis-ci/issues/5290
Our last working bundler version was 1.17.3

Update travis config to solve bundler dependency

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix by limiting bunlder version to be less
than 2.0.0:
https://github.com/travis-ci/travis-ci/issues/5290
Our last working bundler version was 1.17.3
(cherry picked from commit 5e69f86c9b1592e53234d990a42fe77617c85774)

[5.0] Update travis config to solve bundler dependency

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix by limiting bunlder version to be less
than 2.0.0:
https://github.com/travis-ci/travis-ci/issues/5290
Our last working bundler version was 1.17.3
(cherry picked from commit 5e69f86c9b1592e53234d990a42fe77617c85774)

[4.0] Update travis config to solve bundler dependency

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

use re{p,q}.ssl_hello_type correspondingly
https://www.haproxy.org/download/1.7/doc/configuration.txt

haproxy: options re{p,q}_ssl_hello_type are deprecated

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

It turns out that haproxy has a known issue with concurrent connections
when using the sticky-table with size 1 as explained in this [link](https://bugzilla.redhat.com/show_bug.cgi?id=1211781)
Also, there is an scenario using haproxy with galera that keeps the connections 
open to a backend that's declared down. It happens when the health check
fails but the backend still keeps the port open.
This patch fixes both issues increasing the size table to 1000 and
adding an option to shut down the connections once a backend is marked
down.
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>

haproxy: improve galera HA setup (bsc#1122875)

---

chef/cookbooks/haproxy/attributes/default.rb

It looks like this is just limiting the setting tha haproxy chooses
itself based on the amount of memory and features is available (as
can be seen in haproxy -vv ). so we don't have to be picky here.

haproxy: Increase global maxconn limit to 16384

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

It turns out that haproxy has a known issue with concurrent connections
when using the sticky-table with size 1
Also, there is an scenario using galera that keeps the connections open
to a backend that's declared down. It happens when the health check
fails but the backend still keeps the port open.
This patch fixes both issues increasing the size table to 1000 and
adding an option to shutdown the connections once a backend is marked
down.
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>
(cherry picked from commit 0afb9d334bf5f195b065666e099265f4e5db7b05)

[5.0] improve galera HA setup (bsc#1122875)

---

chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

It turns out that haproxy has a known issue with concurrent connections
when using the sticky-table with size 1
Also, there is an scenario using galera that keeps the connections open
to a backend that's declared down. It happens when the health check
fails but the backend still keeps the port open.
This patch fixes both issues increasing the size table to 1000 and
adding an option to shutdown the connections once a backend is marked
down.
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>
(cherry picked from commit 0afb9d334bf5f195b065666e099265f4e5db7b05)

[4.0] improve galera HA setup (bsc#1122875)

---

chef/cookbooks/crowbar-pacemaker/providers/sync_mark.rb
chef/cookbooks/crowbar-pacemaker/resources/sync_mark.rb

This change introduces a new databag item "sync_mark" in "crowbar-config"
databag. It can contain "default_timeout" value and that will be used if
available. Otherwise previous default of 60s will be used.
This is useful in environments where node performance is not consistent.
Such cases were observed in virtualized deployments running on top of cloud
which hosted various other workloads and sometimes non-founders were much
faster than the founder. This lead to situation where some non-founder can
leave "sync window" (with timeout) before the founder even reaches the
"wait" sync_mark.
Another reason for such "inhomogeneous" performance could be (semi)broken
hardware (e.g. RAID cache batteries).
Increasing the default sync_mark timeout in above cases is a workaround
which will "relax" the …

Make default sync_mark timeout configurable + scalable

---

chef/cookbooks/corosync/recipes/service.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-ruby-shadow' not found in package
names`.

corosync: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/corosync/recipes/service.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-ruby-shadow' not found in package
names`.
(cherry picked from commit 607349330facbcced279a30360bf5ef8e73f8cc5)

[5.0] corosync: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/corosync/recipes/service.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-ruby-shadow' not found in package
names`.
(cherry picked from commit 607349330facbcced279a30360bf5ef8e73f8cc5)

[4.0] corosync: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb

When container (group) resource is deleted, it's children are not
and all constraints assigned to the container are re-assigned to one
of the children. In g-haproxy case this leads to incorrect situation
where l-g-haproxy-controller constraint is assigned to
vip-admin-cluster-data.
Removing the constraint before the group should avoid such situations.

[5.0] Drop g-haproxy location before group deletion (bsc#1156914)

---

chef/cookbooks/crowbar-pacemaker/recipes/haproxy.rb

The group was deleted during 7-8 upgrade so this code is not needed
anymore.

Drop g-haproxy removal code (bsc#1156914)

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

If the requests are passed in tcp mode, the source ip gets replaced with
the one of the node where haproxy lives, and there is no way to get the
original ip on the services side.
Add an ability to terminate ssl on haproxy. Using `terminate_ssl` and
`pemfile` will make haproxy switch to http mode and make plain https
requests to the service.

add ssl termination on haproxy (bsc#1149535)

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

If the requests are passed in tcp mode, the source ip gets replaced with
the one of the node where haproxy lives, and there is no way to get the
original ip on the services side.
Add an ability to terminate ssl on haproxy. Using `terminate_ssl` and
`pemfile` will make haproxy switch to http mode and make plain https
requests to the service.
(cherry picked from commit 7e99e40521ebb10e3ab336005843ef0401b558c7)

[5.0] add ssl termination on haproxy (bsc#1149535)

---

chef/cookbooks/haproxy/providers/loadbalancer.rb
chef/cookbooks/haproxy/resources/loadbalancer.rb
chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb

If the requests are passed in tcp mode, the source ip gets replaced with
the one of the node where haproxy lives, and there is no way to get the
original ip on the services side.
Add an ability to terminate ssl on haproxy. Using `terminate_ssl` and
`pemfile` will make haproxy switch to http mode and make plain https
requests to the service.

[4.0] add ssl termination on haproxy (bsc#1149535)
